# 0.9.6~0.9.7 may has bug introduced in
# https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/pull/435/
# and fixed in
# https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/pull/447
# TODO(rmgogogo): update to newer version after PR447.
FROM gcr.io/cloud-marketplace-tools/k8s/deployer_helm/onbuild:0.9.5
