// Code generated by go-swagger; DO NOT EDIT.

package job_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// V2beta1Relationship v2beta1 relationship
// swagger:model v2beta1Relationship
type V2beta1Relationship string

const (

	// V2beta1RelationshipUNKNOWNRELATIONSHIP captures enum value "UNKNOWN_RELATIONSHIP"
	V2beta1RelationshipUNKNOWNRELATIONSHIP V2beta1Relationship = "UNKNOWN_RELATIONSHIP"

	// V2beta1RelationshipOWNER captures enum value "OWNER"
	V2beta1RelationshipOWNER V2beta1Relationship = "OWNER"

	// V2beta1RelationshipCREATOR captures enum value "CREATOR"
	V2beta1RelationshipCREATOR V2beta1Relationship = "CREATOR"
)

// for schema
var v2beta1RelationshipEnum []interface{}

func init() {
	var res []V2beta1Relationship
	if err := json.Unmarshal([]byte(`["UNKNOWN_RELATIONSHIP","OWNER","CREATOR"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v2beta1RelationshipEnum = append(v2beta1RelationshipEnum, v)
	}
}

func (m V2beta1Relationship) validateV2beta1RelationshipEnum(path, location string, value V2beta1Relationship) error {
	if err := validate.Enum(path, location, value, v2beta1RelationshipEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this v2beta1 relationship
func (m V2beta1Relationship) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV2beta1RelationshipEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
