apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-envoy-deployment
  labels:
    component: metadata-envoy
spec:
  template:
    spec:
      containers:
        - name: container
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/envoy/tls
              readOnly: true
            - name: envoy-tls-enabled
              mountPath: /etc/envoy
              readOnly: true
          args:  [  "/etc/envoy/envoy-tls-enabled.yaml" ]
      volumes:
        - name: tls-certs
          secret:
            secretName: kfp-api-tls-cert
        - name: envoy-tls-enabled
          configMap:
            name: envoy-tls-config