apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kfp-api-webhook-cert
spec:
  commonName: ml-pipeline.kubeflow.svc
  dnsNames:
  - ml-pipeline
  - ml-pipeline.kubeflow.svc
  - ml-pipeline.kubeflow.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kfp-api-webhook-selfsigned-issuer
  secretName: kfp-api-webhook-cert
