// Copyright 2018 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package server

import (
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	apiv2beta1 "github.com/kubeflow/pipelines/backend/api/v2beta1/go_client"
	"github.com/kubeflow/pipelines/backend/src/apiserver/list"
	"github.com/kubeflow/pipelines/backend/src/apiserver/model"
	"github.com/kubeflow/pipelines/backend/src/common/util"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/grpc/codes"
	"google.golang.org/protobuf/testing/protocmp"
)

func TestValidateFilterV2Beta1ArtifactTask_RejectsEmptyIDs(t *testing.T) {
	_, err := validateFilterV2Beta1ArtifactTask(nil, []string{""}, nil)
	require.Error(t, err)
	assert.Equal(t, codes.InvalidArgument, err.(*util.UserError).ExternalStatusCode())
	assert.Contains(t, err.Error(), "run_ids must not contain empty values")

	_, err = validateFilterV2Beta1ArtifactTask([]string{""}, nil, nil)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "task_ids must not contain empty values")

	_, err = validateFilterV2Beta1ArtifactTask(nil, nil, []string{""})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "artifact_ids must not contain empty values")
}

func TestValidateFilterV2Beta1ArtifactTask_RejectsNoFilters(t *testing.T) {
	_, err := validateFilterV2Beta1ArtifactTask(nil, nil, nil)
	require.Error(t, err)
	assert.Equal(t, codes.InvalidArgument, err.(*util.UserError).ExternalStatusCode())
	assert.Contains(t, err.Error(), "At least one filter")
}

func TestValidateFilterV2Beta1ArtifactTask_BuildsFilters(t *testing.T) {
	filters, err := validateFilterV2Beta1ArtifactTask([]string{"task-1"}, []string{"run-1"}, []string{"artifact-1"})
	require.NoError(t, err)
	require.Len(t, filters, 3)
	assert.Equal(t, model.TaskResourceType, filters[0].Type)
	assert.Equal(t, "task-1", filters[0].ID)
	assert.Equal(t, model.RunResourceType, filters[1].Type)
	assert.Equal(t, "run-1", filters[1].ID)
	assert.Equal(t, model.ArtifactResourceType, filters[2].Type)
	assert.Equal(t, "artifact-1", filters[2].ID)
}

func TestTransformJSONForBackwardCompatibility(t *testing.T) {
	tests := []struct {
		name      string
		input     string
		expected  string
		expectErr bool
	}{
		{
			name:      "Standard case with multiple replacements",
			input:     `{"intValue": 1, "stringValue": "test", "longValue": 1234567890}`,
			expected:  `{"int_value": 1, "string_value": "test", "long_value": 1234567890}`,
			expectErr: false,
		},
		{
			name:      "No replacements needed",
			input:     `{"int_value": 1, "string_value": "test", "long_value": 1234567890}`,
			expected:  `{"int_value": 1, "string_value": "test", "long_value": 1234567890}`,
			expectErr: false,
		},
		{
			name:      "Empty input",
			input:     ``,
			expected:  ``,
			expectErr: false,
		},
		{
			name:      "Nested JSON structure",
			input:     `{"data": {"intValue": 5, "stringValue": "nested"}}`,
			expected:  `{"data": {"int_value": 5, "string_value": "nested"}}`,
			expectErr: false,
		},
		{
			name:      "Input with no recognized fields",
			input:     `{"otherValue": "value"}`,
			expected:  `{"otherValue": "value"}`,
			expectErr: false,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result, err := transformJSONForBackwardCompatibility(test.input)

			if test.expectErr {
				assert.NotNil(t, err, "Expected an error but got none")
				return
			}

			assert.Nil(t, err, "Expected no error but got: %+v", err)
			assert.Equal(t, test.expected, result, "Unexpected result for input: %v", test.input)
		})
	}
}
func TestParseAPIFilter_EmptyStringYieldsNilFilter(t *testing.T) {
	f, err := parseAPIFilter("")
	assert.Nil(t, err)
	assert.Nil(t, f)

	f, err = parseAPIFilter("")
	assert.Nil(t, err)
	assert.Nil(t, f)
}

func TestParseAPIFilter_InvalidStringYieldsError(t *testing.T) {
	f, err := parseAPIFilter("lkjlkjlkj")
	assert.NotNil(t, err)
	assert.Nil(t, f)

	f, err = parseAPIFilter("lkjlkjlkj")
	assert.NotNil(t, err)
	assert.Nil(t, f)
}

func TestParseAPIFilter_DecodesEncodedStringMigrated(t *testing.T) {
	// in was generated by calling JSON.stringify followed by encodeURIComponent in
	// the browser on the following JSON string:
	//   {"predicates":[{"operation":"EQUALS","key":"testkey","stringValue":"testvalue"}]}

	in := "%7B%22predicates%22%3A%5B%7B%22operation%22%3A%22EQUALS%22%2C%22key%22%3A%22testkey%22%2C%22stringValue%22%3A%22testvalue%22%7D%5D%7D"

	// The above should correspond the following filter:
	want := &apiv2beta1.Filter{
		Predicates: []*apiv2beta1.Predicate{
			{
				Key: "testkey", Operation: apiv2beta1.Predicate_EQUALS,
				Value: &apiv2beta1.Predicate_StringValue{StringValue: "testvalue"},
			},
		},
	}

	got, err := parseAPIFilter(in)
	if !cmp.Equal(got, want, cmpopts.EquateEmpty(), protocmp.Transform()) || err != nil {
		t.Errorf("parseAPIString(%q) =\nGot %+v, %v\n Want %+v, <nil>\nDiff: %s",
			in, got, err, want, cmp.Diff(want, got))
	}
}

func TestParseAPIFilter_DecodesEncodedString(t *testing.T) {
	// in was generated by calling JSON.stringify followed by encodeURIComponent in
	// the browser on the following JSON string:
	//   {"predicates":[{"operation":"EQUALS","key":"testkey","stringValue":"testvalue"}]}

	in := "%7B%22predicates%22%3A%5B%7B%22operation%22%3A%22EQUALS%22%2C%22key%22%3A%22testkey%22%2C%22stringValue%22%3A%22testvalue%22%7D%5D%7D"

	// The above should correspond the following filter:
	want := &apiv2beta1.Filter{
		Predicates: []*apiv2beta1.Predicate{
			{
				Key: "testkey", Operation: apiv2beta1.Predicate_EQUALS,
				Value: &apiv2beta1.Predicate_StringValue{StringValue: "testvalue"},
			},
		},
	}

	got, err := parseAPIFilter(in)
	if !cmp.Equal(got, want, cmpopts.EquateEmpty(), protocmp.Transform()) || err != nil {
		t.Errorf("parseAPIString(%q) =\nGot %+v, %v\n Want %+v, <nil>\nDiff: %s",
			in, got, err, want, cmp.Diff(want, got))
	}
}

type fakeListable struct {
	PrimaryKey       string
	FakeName         string
	CreatedTimestamp int64
}

func (f *fakeListable) PrimaryKeyColumnName() string {
	return "PrimaryKey"
}

func (f *fakeListable) DefaultSortField() string {
	return "CreatedTimestamp"
}

var fakeAPIToModelMap = map[string]string{
	"timestamp": "CreatedTimestamp",
	"name":      "FakeName",
	"id":        "PrimaryKey",
}

func (f *fakeListable) APIToModelFieldMap() map[string]string {
	return fakeAPIToModelMap
}

func (f *fakeListable) GetModelName() string {
	return ""
}

func (f *fakeListable) GetField(name string) (string, string, bool) {
	if field, ok := fakeAPIToModelMap[name]; ok {
		return field, field, true
	} else {
		return "", "", false
	}
}

func (f *fakeListable) GetFieldValue(name string) interface{} {
	switch name {
	case "CreatedTimestamp":
		return f.CreatedTimestamp
	case "FakeName":
		return f.FakeName
	case "PrimaryKey":
		return f.PrimaryKey
	}
	return nil
}

func (f *fakeListable) GetSortByFieldPrefix(name string) string {
	return ""
}

func (f *fakeListable) GetKeyFieldPrefix() string {
	return ""
}

func (f *fakeListable) CaseInsensitiveFields() map[string]struct{} {
	return map[string]struct{}{"name": {}}
}

func TestValidatedListOptions_Errors(t *testing.T) {
	opts, err := list.NewOptions(&fakeListable{}, 10, "name asc", nil)
	if err != nil {
		t.Fatalf("list.NewOptions() = _, %+v; Want nil error", err)
	}

	npt, err := opts.NextPageToken(&fakeListable{})
	if err != nil {
		t.Fatalf("opt.NextPageToken() = _, %+v; Want nil error", err)
	}

	_, err = validatedListOptions(&fakeListable{}, npt, 10, "name asc", "")
	if err != nil {
		t.Fatalf("validatedListOptions(fakeListable, 10, \"name asc\") = _, %+v; Want nil error", err)
	}

	_, err = validatedListOptions(&fakeListable{}, npt, 10, "name asc", "")
	if err != nil {
		t.Fatalf("validatedListOptions(fakeListable, 10, \"name asc\") = _, %+v; Want nil error", err)
	}

	_, err = validatedListOptions(&fakeListable{}, npt, 10, "name desc", "")
	if err == nil {
		t.Fatalf("validatedListOptions(fakeListable, 10, \"name desc\") = _, %+v; Want error", err)
	}

	_, err = validatedListOptions(&fakeListable{}, npt, 10, "name desc", "")
	if err == nil {
		t.Fatalf("validatedListOptions(fakeListable, 10, \"name desc\") = _, %+v; Want error", err)
	}
}
