// Code generated by go-swagger; DO NOT EDIT.

package run_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubeflow/pipelines/backend/api/v2beta1/go_http_client/run_model"
)

// RunServiceTerminateRunReader is a Reader for the RunServiceTerminateRun structure.
type RunServiceTerminateRunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RunServiceTerminateRunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRunServiceTerminateRunOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRunServiceTerminateRunDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRunServiceTerminateRunOK creates a RunServiceTerminateRunOK with default headers values
func NewRunServiceTerminateRunOK() *RunServiceTerminateRunOK {
	return &RunServiceTerminateRunOK{}
}

/*
RunServiceTerminateRunOK describes a response with status code 200, with default header values.

A successful response.
*/
type RunServiceTerminateRunOK struct {
	Payload interface{}
}

// IsSuccess returns true when this run service terminate run o k response has a 2xx status code
func (o *RunServiceTerminateRunOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this run service terminate run o k response has a 3xx status code
func (o *RunServiceTerminateRunOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this run service terminate run o k response has a 4xx status code
func (o *RunServiceTerminateRunOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this run service terminate run o k response has a 5xx status code
func (o *RunServiceTerminateRunOK) IsServerError() bool {
	return false
}

// IsCode returns true when this run service terminate run o k response a status code equal to that given
func (o *RunServiceTerminateRunOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the run service terminate run o k response
func (o *RunServiceTerminateRunOK) Code() int {
	return 200
}

func (o *RunServiceTerminateRunOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apis/v2beta1/runs/{run_id}:terminate][%d] runServiceTerminateRunOK %s", 200, payload)
}

func (o *RunServiceTerminateRunOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apis/v2beta1/runs/{run_id}:terminate][%d] runServiceTerminateRunOK %s", 200, payload)
}

func (o *RunServiceTerminateRunOK) GetPayload() interface{} {
	return o.Payload
}

func (o *RunServiceTerminateRunOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunServiceTerminateRunDefault creates a RunServiceTerminateRunDefault with default headers values
func NewRunServiceTerminateRunDefault(code int) *RunServiceTerminateRunDefault {
	return &RunServiceTerminateRunDefault{
		_statusCode: code,
	}
}

/*
RunServiceTerminateRunDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RunServiceTerminateRunDefault struct {
	_statusCode int

	Payload *run_model.GooglerpcStatus
}

// IsSuccess returns true when this run service terminate run default response has a 2xx status code
func (o *RunServiceTerminateRunDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this run service terminate run default response has a 3xx status code
func (o *RunServiceTerminateRunDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this run service terminate run default response has a 4xx status code
func (o *RunServiceTerminateRunDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this run service terminate run default response has a 5xx status code
func (o *RunServiceTerminateRunDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this run service terminate run default response a status code equal to that given
func (o *RunServiceTerminateRunDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the run service terminate run default response
func (o *RunServiceTerminateRunDefault) Code() int {
	return o._statusCode
}

func (o *RunServiceTerminateRunDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apis/v2beta1/runs/{run_id}:terminate][%d] RunService_TerminateRun default %s", o._statusCode, payload)
}

func (o *RunServiceTerminateRunDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apis/v2beta1/runs/{run_id}:terminate][%d] RunService_TerminateRun default %s", o._statusCode, payload)
}

func (o *RunServiceTerminateRunDefault) GetPayload() *run_model.GooglerpcStatus {
	return o.Payload
}

func (o *RunServiceTerminateRunDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(run_model.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
