[tox]
envlist = py27, py3
skip_missing_interpreters = true

[testenv]
deps=
     certifi >= 14.05.14
     future; python_version<="2.7"
     six >= 1.10
     python_dateutil >= 2.5.3
     setuptools >= 21.0.0
     urllib3 >= 1.15.1
     pytest==4.6.11
     pytest-cov<3
     pytest-randomly==1.2.3

commands=
   pytest --cov=kfp_server_api
