[tox]
envlist = py27, py3

[testenv]
deps=
     certifi >= 14.05.14
     future; python_version<="2.7"
     six >= 1.10
     python_dateutil >= 2.5.3
     setuptools >= 21.0.0
     urllib3 >= 1.15.1
     pytest~=4.6.7
     pytest-cov>=2.8.1
     pytest-randomly==1.2.3

commands=
   pytest --cov=kfp_server_api
