// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePipelineVersionV1Params creates a new DeletePipelineVersionV1Params object
// with the default values initialized.
func NewDeletePipelineVersionV1Params() *DeletePipelineVersionV1Params {
	var ()
	return &DeletePipelineVersionV1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePipelineVersionV1ParamsWithTimeout creates a new DeletePipelineVersionV1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePipelineVersionV1ParamsWithTimeout(timeout time.Duration) *DeletePipelineVersionV1Params {
	var ()
	return &DeletePipelineVersionV1Params{

		timeout: timeout,
	}
}

// NewDeletePipelineVersionV1ParamsWithContext creates a new DeletePipelineVersionV1Params object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePipelineVersionV1ParamsWithContext(ctx context.Context) *DeletePipelineVersionV1Params {
	var ()
	return &DeletePipelineVersionV1Params{

		Context: ctx,
	}
}

// NewDeletePipelineVersionV1ParamsWithHTTPClient creates a new DeletePipelineVersionV1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePipelineVersionV1ParamsWithHTTPClient(client *http.Client) *DeletePipelineVersionV1Params {
	var ()
	return &DeletePipelineVersionV1Params{
		HTTPClient: client,
	}
}

/*DeletePipelineVersionV1Params contains all the parameters to send to the API endpoint
for the delete pipeline version v1 operation typically these are written to a http.Request
*/
type DeletePipelineVersionV1Params struct {

	/*VersionID
	  The ID of the pipeline version to be deleted.

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete pipeline version v1 params
func (o *DeletePipelineVersionV1Params) WithTimeout(timeout time.Duration) *DeletePipelineVersionV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete pipeline version v1 params
func (o *DeletePipelineVersionV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete pipeline version v1 params
func (o *DeletePipelineVersionV1Params) WithContext(ctx context.Context) *DeletePipelineVersionV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete pipeline version v1 params
func (o *DeletePipelineVersionV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete pipeline version v1 params
func (o *DeletePipelineVersionV1Params) WithHTTPClient(client *http.Client) *DeletePipelineVersionV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete pipeline version v1 params
func (o *DeletePipelineVersionV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVersionID adds the versionID to the delete pipeline version v1 params
func (o *DeletePipelineVersionV1Params) WithVersionID(versionID string) *DeletePipelineVersionV1Params {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the delete pipeline version v1 params
func (o *DeletePipelineVersionV1Params) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePipelineVersionV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param version_id
	if err := r.SetPathParam("version_id", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
