// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	pipeline_model "github.com/kubeflow/pipelines/backend/api/v1beta1/go_http_client/pipeline_model"
)

// PipelineServiceGetPipelineVersionTemplateReader is a Reader for the PipelineServiceGetPipelineVersionTemplate structure.
type PipelineServiceGetPipelineVersionTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PipelineServiceGetPipelineVersionTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPipelineServiceGetPipelineVersionTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPipelineServiceGetPipelineVersionTemplateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPipelineServiceGetPipelineVersionTemplateOK creates a PipelineServiceGetPipelineVersionTemplateOK with default headers values
func NewPipelineServiceGetPipelineVersionTemplateOK() *PipelineServiceGetPipelineVersionTemplateOK {
	return &PipelineServiceGetPipelineVersionTemplateOK{}
}

/*PipelineServiceGetPipelineVersionTemplateOK handles this case with default header values.

A successful response.
*/
type PipelineServiceGetPipelineVersionTemplateOK struct {
	Payload *pipeline_model.APIGetTemplateResponse
}

func (o *PipelineServiceGetPipelineVersionTemplateOK) Error() string {
	return fmt.Sprintf("[GET /apis/v1beta1/pipeline_versions/{version_id}/templates][%d] pipelineServiceGetPipelineVersionTemplateOK  %+v", 200, o.Payload)
}

func (o *PipelineServiceGetPipelineVersionTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_model.APIGetTemplateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPipelineServiceGetPipelineVersionTemplateDefault creates a PipelineServiceGetPipelineVersionTemplateDefault with default headers values
func NewPipelineServiceGetPipelineVersionTemplateDefault(code int) *PipelineServiceGetPipelineVersionTemplateDefault {
	return &PipelineServiceGetPipelineVersionTemplateDefault{
		_statusCode: code,
	}
}

/*PipelineServiceGetPipelineVersionTemplateDefault handles this case with default header values.

An unexpected error response.
*/
type PipelineServiceGetPipelineVersionTemplateDefault struct {
	_statusCode int

	Payload *pipeline_model.GatewayruntimeError
}

// Code gets the status code for the pipeline service get pipeline version template default response
func (o *PipelineServiceGetPipelineVersionTemplateDefault) Code() int {
	return o._statusCode
}

func (o *PipelineServiceGetPipelineVersionTemplateDefault) Error() string {
	return fmt.Sprintf("[GET /apis/v1beta1/pipeline_versions/{version_id}/templates][%d] PipelineService_GetPipelineVersionTemplate default  %+v", o._statusCode, o.Payload)
}

func (o *PipelineServiceGetPipelineVersionTemplateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
