// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubeflow/pipelines/backend/api/v1beta1/go_http_client/pipeline_model"
)

// PipelineServiceCreatePipelineVersionV1Reader is a Reader for the PipelineServiceCreatePipelineVersionV1 structure.
type PipelineServiceCreatePipelineVersionV1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PipelineServiceCreatePipelineVersionV1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPipelineServiceCreatePipelineVersionV1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPipelineServiceCreatePipelineVersionV1Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPipelineServiceCreatePipelineVersionV1OK creates a PipelineServiceCreatePipelineVersionV1OK with default headers values
func NewPipelineServiceCreatePipelineVersionV1OK() *PipelineServiceCreatePipelineVersionV1OK {
	return &PipelineServiceCreatePipelineVersionV1OK{}
}

/*
PipelineServiceCreatePipelineVersionV1OK describes a response with status code 200, with default header values.

A successful response.
*/
type PipelineServiceCreatePipelineVersionV1OK struct {
	Payload *pipeline_model.APIPipelineVersion
}

// IsSuccess returns true when this pipeline service create pipeline version v1 o k response has a 2xx status code
func (o *PipelineServiceCreatePipelineVersionV1OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pipeline service create pipeline version v1 o k response has a 3xx status code
func (o *PipelineServiceCreatePipelineVersionV1OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pipeline service create pipeline version v1 o k response has a 4xx status code
func (o *PipelineServiceCreatePipelineVersionV1OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pipeline service create pipeline version v1 o k response has a 5xx status code
func (o *PipelineServiceCreatePipelineVersionV1OK) IsServerError() bool {
	return false
}

// IsCode returns true when this pipeline service create pipeline version v1 o k response a status code equal to that given
func (o *PipelineServiceCreatePipelineVersionV1OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the pipeline service create pipeline version v1 o k response
func (o *PipelineServiceCreatePipelineVersionV1OK) Code() int {
	return 200
}

func (o *PipelineServiceCreatePipelineVersionV1OK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apis/v1beta1/pipeline_versions][%d] pipelineServiceCreatePipelineVersionV1OK %s", 200, payload)
}

func (o *PipelineServiceCreatePipelineVersionV1OK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apis/v1beta1/pipeline_versions][%d] pipelineServiceCreatePipelineVersionV1OK %s", 200, payload)
}

func (o *PipelineServiceCreatePipelineVersionV1OK) GetPayload() *pipeline_model.APIPipelineVersion {
	return o.Payload
}

func (o *PipelineServiceCreatePipelineVersionV1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_model.APIPipelineVersion)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPipelineServiceCreatePipelineVersionV1Default creates a PipelineServiceCreatePipelineVersionV1Default with default headers values
func NewPipelineServiceCreatePipelineVersionV1Default(code int) *PipelineServiceCreatePipelineVersionV1Default {
	return &PipelineServiceCreatePipelineVersionV1Default{
		_statusCode: code,
	}
}

/*
PipelineServiceCreatePipelineVersionV1Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PipelineServiceCreatePipelineVersionV1Default struct {
	_statusCode int

	Payload *pipeline_model.GooglerpcStatus
}

// IsSuccess returns true when this pipeline service create pipeline version v1 default response has a 2xx status code
func (o *PipelineServiceCreatePipelineVersionV1Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this pipeline service create pipeline version v1 default response has a 3xx status code
func (o *PipelineServiceCreatePipelineVersionV1Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this pipeline service create pipeline version v1 default response has a 4xx status code
func (o *PipelineServiceCreatePipelineVersionV1Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this pipeline service create pipeline version v1 default response has a 5xx status code
func (o *PipelineServiceCreatePipelineVersionV1Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this pipeline service create pipeline version v1 default response a status code equal to that given
func (o *PipelineServiceCreatePipelineVersionV1Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the pipeline service create pipeline version v1 default response
func (o *PipelineServiceCreatePipelineVersionV1Default) Code() int {
	return o._statusCode
}

func (o *PipelineServiceCreatePipelineVersionV1Default) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apis/v1beta1/pipeline_versions][%d] PipelineService_CreatePipelineVersionV1 default %s", o._statusCode, payload)
}

func (o *PipelineServiceCreatePipelineVersionV1Default) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apis/v1beta1/pipeline_versions][%d] PipelineService_CreatePipelineVersionV1 default %s", o._statusCode, payload)
}

func (o *PipelineServiceCreatePipelineVersionV1Default) GetPayload() *pipeline_model.GooglerpcStatus {
	return o.Payload
}

func (o *PipelineServiceCreatePipelineVersionV1Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_model.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
