apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipeline-parallel-for-mount-pvc-
spec:
  arguments:
    parameters:
    - name: components-98f254581598234b59377784d6cbf209de79e0bcda8013fe4c4397b5d3a26767
      value: '{"executorLabel":"exec-createpvc","inputDefinitions":{"parameters":{"access_modes":{"description":"AccessModes
        to request for the provisioned PVC. May\nbe one or more of ``''ReadWriteOnce''``,
        ``''ReadOnlyMany''``, ``''ReadWriteMany''``, or\n``''ReadWriteOncePod''``.
        Corresponds to `PersistentVolumeClaim.spec.accessModes \u003chttps://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes\u003e`_.","parameterType":"LIST"},"annotations":{"description":"Annotations
        for the PVC''s metadata. Corresponds to `PersistentVolumeClaim.metadata.annotations
        \u003chttps://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/#PersistentVolumeClaim\u003e`_.","isOptional":true,"parameterType":"STRUCT"},"pvc_name":{"description":"Name
        of the PVC. Corresponds to `PersistentVolumeClaim.metadata.name \u003chttps://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/#PersistentVolumeClaim\u003e`_.
        Only one of ``pvc_name`` and ``pvc_name_suffix`` can\nbe provided.","isOptional":true,"parameterType":"STRING"},"pvc_name_suffix":{"description":"Prefix
        to use for a dynamically generated name, which\nwill take the form ``\u003cargo-workflow-name\u003e-\u003cpvc_name_suffix\u003e``.
        Only one\nof ``pvc_name`` and ``pvc_name_suffix`` can be provided.","isOptional":true,"parameterType":"STRING"},"size":{"description":"The
        size of storage requested by the PVC that will be provisioned. For example,
        ``''5Gi''``. Corresponds to `PersistentVolumeClaim.spec.resources.requests.storage
        \u003chttps://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/#PersistentVolumeClaimSpec\u003e`_.","parameterType":"STRING"},"storage_class_name":{"defaultValue":"","description":"Name
        of StorageClass from which to provision the PV\nto back the PVC. ``None``
        indicates to use the cluster''s default\nstorage_class_name. Set to ``''''``
        for a statically specified PVC.","isOptional":true,"parameterType":"STRING"},"volume_name":{"description":"Pre-existing
        PersistentVolume that should back the\nprovisioned PersistentVolumeClaim.
        Used for statically\nspecified PV only. Corresponds to `PersistentVolumeClaim.spec.volumeName
        \u003chttps://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/#PersistentVolumeClaimSpec\u003e`_.","isOptional":true,"parameterType":"STRING"}}},"outputDefinitions":{"parameters":{"name":{"parameterType":"STRING"}}}}'
    - name: implementations-98f254581598234b59377784d6cbf209de79e0bcda8013fe4c4397b5d3a26767
      value: '{"image":"argostub/createpvc"}'
    - name: kubernetes-comp-example-component
      value: '{"pvcMount":[{"componentInputParameter":"pipelinechannel--createpvc-name","mountPath":"/data","pvcNameParameter":{"componentInputParameter":"pipelinechannel--createpvc-name"}}]}'
    - name: components-1e6d3fc350583cb591281c08420927b09565ea68a8ea52650e820b1ed008f913
      value: '{"executorLabel":"exec-example-component","inputDefinitions":{"parameters":{"item":{"parameterType":"STRING"}}},"outputDefinitions":{"parameters":{"Output":{"parameterType":"STRING"}}}}'
    - name: implementations-1e6d3fc350583cb591281c08420927b09565ea68a8ea52650e820b1ed008f913
      value: '{"args":["--executor_input","{{$}}","--function_to_execute","example_component"],"command":["sh","-c","\nif
        ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip || python3
        -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1
        python3 -m pip install --quiet --no-warn-script-location ''kfp==2.15.2'' ''--no-deps''
        ''typing-extensions\u003e=3.7.4,\u003c5; python_version\u003c\"3.9\"'' \u0026\u0026
        \"$0\" \"$@\"\n","sh","-ec","program_path=$(mktemp -d)\n\nprintf \"%s\" \"$0\"
        \u003e \"$program_path/ephemeral_component.py\"\n_KFP_RUNTIME=true python3
        -m kfp.dsl.executor_main                         --component_module_path                         \"$program_path/ephemeral_component.py\"                         \"$@\"\n","\nimport
        kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import *\n\ndef
        example_component(item: str) -\u003e str:\n    print(f\"Item: {item}\")\n    return
        item\n\n"],"image":"python:3.11"}'
    - name: components-comp-for-loop-2
      value: '{"dag":{"tasks":{"example-component":{"cachingOptions":{"enableCache":true},"componentRef":{"name":"comp-example-component"},"inputs":{"parameters":{"item":{"componentInputParameter":"pipelinechannel--loop-item-param-1"}}},"taskInfo":{"name":"example-component"}}}},"inputDefinitions":{"parameters":{"pipelinechannel--createpvc-name":{"parameterType":"STRING"},"pipelinechannel--loop-item-param-1":{"parameterType":"STRING"}}}}'
    - name: components-root
      value: '{"dag":{"tasks":{"createpvc":{"cachingOptions":{"enableCache":true},"componentRef":{"name":"comp-createpvc"},"inputs":{"parameters":{"access_modes":{"runtimeValue":{"constant":["ReadWriteOnce"]}},"pvc_name_suffix":{"runtimeValue":{"constant":"-my-pvc"}},"size":{"runtimeValue":{"constant":"5Mi"}},"storage_class_name":{"runtimeValue":{"constant":"standard"}}}},"taskInfo":{"name":"createpvc"}},"for-loop-2":{"componentRef":{"name":"comp-for-loop-2"},"dependentTasks":["createpvc"],"inputs":{"parameters":{"pipelinechannel--createpvc-name":{"taskOutputParameter":{"outputParameterKey":"name","producerTask":"createpvc"}}}},"parameterIterator":{"itemInput":"pipelinechannel--loop-item-param-1","items":{"raw":"[\"a\"]"}},"taskInfo":{"name":"for-loop-2"}}}},"inputDefinitions":{"parameters":{"my_pvc_name_suffix":{"defaultValue":"test-pvc","isOptional":true,"parameterType":"STRING"}}}}'
  entrypoint: entrypoint
  podMetadata:
    annotations:
      pipelines.kubeflow.org/v2_component: "true"
      sidecar.istio.io/inject: "false"
    labels:
      pipelines.kubeflow.org/v2_component: "true"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: pipeline-runner
  templates:
  - inputs:
      parameters:
      - name: component
      - name: task
      - name: container
      - name: task-name
      - name: parent-dag-id
      - default: "-1"
        name: iteration-index
      - default: ""
        name: kubernetes-config
    metadata: {}
    name: system-container-driver
    outputs:
      parameters:
      - name: pod-spec-patch
        valueFrom:
          default: ""
          jsonPath: $.pod-spec-patch
      - default: "false"
        name: cached-decision
        valueFrom:
          default: "false"
          jsonPath: $.cached-decision
      - name: condition
        valueFrom:
          default: "true"
          jsonPath: $.condition
    plugin:
      driver-plugin:
        args:
          cache_disabled: false
          cached_decision_path: '{{outputs.parameters.cached-decision.path}}'
          component: '{{inputs.parameters.component}}'
          condition_path: '{{outputs.parameters.condition.path}}'
          container: '{{inputs.parameters.container}}'
          dag_execution_id: '{{inputs.parameters.parent-dag-id}}'
          http_proxy: ""
          https_proxy: ""
          iteration_index: '{{inputs.parameters.iteration-index}}'
          kubernetes_config: '{{inputs.parameters.kubernetes-config}}'
          metadata_tls_enabled: false
          ml_pipeline_server_address: ml-pipeline.kubeflow.svc.cluster.local
          ml_pipeline_server_port: "8887"
          ml_pipeline_tls_enabled: false
          mlmd_server_address: metadata-grpc-service.kubeflow.svc.cluster.local
          mlmd_server_port: "8080"
          no_proxy: ""
          pipeline_name: pipeline-parallel-for-mount-pvc
          pod_spec_patch_path: '{{outputs.parameters.pod-spec-patch.path}}'
          run_display_name: ""
          run_id: '{{workflow.uid}}'
          run_name: '{{workflow.name}}'
          task: '{{inputs.parameters.task}}'
          task_name: '{{inputs.parameters.task-name}}'
          type: CONTAINER
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: pod-spec-patch
            value: '{{inputs.parameters.pod-spec-patch}}'
        name: executor
        template: system-container-impl
        when: '{{inputs.parameters.cached-decision}} != true'
    inputs:
      parameters:
      - name: pod-spec-patch
      - default: "false"
        name: cached-decision
    metadata: {}
    name: system-container-executor
    outputs: {}
  - container:
      command:
      - should-be-overridden-during-runtime
      env:
      - name: KFP_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: KFP_POD_UID
        valueFrom:
          fieldRef:
            fieldPath: metadata.uid
      envFrom:
      - configMapRef:
          name: metadata-grpc-configmap
          optional: true
      image: gcr.io/ml-pipeline/should-be-overridden-during-runtime
      name: ""
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
      - mountPath: /kfp-launcher
        name: kfp-launcher
      - mountPath: /gcs
        name: gcs-scratch
      - mountPath: /s3
        name: s3-scratch
      - mountPath: /minio
        name: minio-scratch
      - mountPath: /.local
        name: dot-local-scratch
      - mountPath: /.cache
        name: dot-cache-scratch
      - mountPath: /.config
        name: dot-config-scratch
    initContainers:
    - args:
      - --copy
      - /kfp-launcher/launch
      command:
      - launcher-v2
      image: ghcr.io/kubeflow/kfp-launcher:latest
      name: kfp-launcher
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
      - mountPath: /kfp-launcher
        name: kfp-launcher
    inputs:
      parameters:
      - name: pod-spec-patch
    metadata: {}
    name: system-container-impl
    outputs: {}
    podSpecPatch: '{{inputs.parameters.pod-spec-patch}}'
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    volumes:
    - emptyDir: {}
      name: kfp-launcher
    - emptyDir: {}
      name: gcs-scratch
    - emptyDir: {}
      name: s3-scratch
    - emptyDir: {}
      name: minio-scratch
    - emptyDir: {}
      name: dot-local-scratch
    - emptyDir: {}
      name: dot-cache-scratch
    - emptyDir: {}
      name: dot-config-scratch
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: component
            value: '{{workflow.parameters.components-1e6d3fc350583cb591281c08420927b09565ea68a8ea52650e820b1ed008f913}}'
          - name: task
            value: '{"cachingOptions":{"enableCache":true},"componentRef":{"name":"comp-example-component"},"inputs":{"parameters":{"item":{"componentInputParameter":"pipelinechannel--loop-item-param-1"}}},"taskInfo":{"name":"example-component"}}'
          - name: container
            value: '{{workflow.parameters.implementations-1e6d3fc350583cb591281c08420927b09565ea68a8ea52650e820b1ed008f913}}'
          - name: task-name
            value: example-component
          - name: parent-dag-id
            value: '{{inputs.parameters.parent-dag-id}}'
          - name: kubernetes-config
            value: '{{workflow.parameters.kubernetes-comp-example-component}}'
        name: example-component-driver
        template: system-container-driver
      - arguments:
          parameters:
          - name: pod-spec-patch
            value: '{{tasks.example-component-driver.outputs.parameters.pod-spec-patch}}'
          - default: "false"
            name: cached-decision
            value: '{{tasks.example-component-driver.outputs.parameters.cached-decision}}'
        depends: example-component-driver.Succeeded
        name: example-component
        template: system-container-executor
    inputs:
      parameters:
      - name: parent-dag-id
    metadata: {}
    name: comp-for-loop-2
    outputs: {}
  - inputs:
      parameters:
      - name: component
      - default: ""
        name: runtime-config
      - default: ""
        name: task
      - default: ""
        name: task-name
      - default: "0"
        name: parent-dag-id
      - default: "-1"
        name: iteration-index
      - default: DAG
        name: driver-type
    metadata: {}
    name: system-dag-driver
    outputs:
      parameters:
      - name: execution-id
        valueFrom:
          jsonPath: $.execution-id
      - name: iteration-count
        valueFrom:
          default: "0"
          jsonPath: $.iteration-count
      - name: condition
        valueFrom:
          default: "true"
          jsonPath: $.condition
    plugin:
      driver-plugin:
        args:
          cache_disabled: false
          component: '{{inputs.parameters.component}}'
          condition_path: '{{outputs.parameters.condition.path}}'
          dag_execution_id: '{{inputs.parameters.parent-dag-id}}'
          execution_id_path: '{{outputs.parameters.execution-id.path}}'
          http_proxy: ""
          https_proxy: ""
          iteration_count_path: '{{outputs.parameters.iteration-count.path}}'
          iteration_index: '{{inputs.parameters.iteration-index}}'
          metadata_tls_enabled: false
          ml_pipeline_server_address: ml-pipeline.kubeflow.svc.cluster.local
          ml_pipeline_server_port: "8887"
          ml_pipeline_tls_enabled: false
          mlmd_server_address: metadata-grpc-service.kubeflow.svc.cluster.local
          mlmd_server_port: "8080"
          no_proxy: ""
          pipeline_name: pipeline-parallel-for-mount-pvc
          run_display_name: ""
          run_id: '{{workflow.uid}}'
          run_name: '{{workflow.name}}'
          runtime_config: '{{inputs.parameters.runtime-config}}'
          task: '{{inputs.parameters.task}}'
          task_name: '{{inputs.parameters.task-name}}'
          type: '{{inputs.parameters.driver-type}}'
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: component
            value: '{{workflow.parameters.components-comp-for-loop-2}}'
          - name: iteration-index
            value: '{{inputs.parameters.iteration-index}}'
          - name: parent-dag-id
            value: '{{inputs.parameters.parent-dag-id}}'
          - name: task
            value: '{"componentRef":{"name":"comp-for-loop-2"},"dependentTasks":["createpvc"],"inputs":{"parameters":{"pipelinechannel--createpvc-name":{"taskOutputParameter":{"outputParameterKey":"name","producerTask":"createpvc"}}}},"parameterIterator":{"itemInput":"pipelinechannel--loop-item-param-1","items":{"raw":"[\"a\"]"}},"taskInfo":{"name":"for-loop-2"}}'
          - name: task-name
            value: for-loop-2
        name: iteration-item-driver
        template: system-dag-driver
      - arguments:
          parameters:
          - name: parent-dag-id
            value: '{{tasks.iteration-item-driver.outputs.parameters.execution-id}}'
          - name: condition
            value: '{{tasks.iteration-item-driver.outputs.parameters.condition}}'
        depends: iteration-item-driver.Succeeded
        name: iteration-item
        template: comp-for-loop-2
    inputs:
      parameters:
      - name: parent-dag-id
      - name: iteration-index
    metadata: {}
    name: comp-for-loop-2-iteration
    outputs: {}
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: component
            value: '{{workflow.parameters.components-comp-for-loop-2}}'
          - name: parent-dag-id
            value: '{{inputs.parameters.parent-dag-id}}'
          - name: task
            value: '{"componentRef":{"name":"comp-for-loop-2"},"dependentTasks":["createpvc"],"inputs":{"parameters":{"pipelinechannel--createpvc-name":{"taskOutputParameter":{"outputParameterKey":"name","producerTask":"createpvc"}}}},"parameterIterator":{"itemInput":"pipelinechannel--loop-item-param-1","items":{"raw":"[\"a\"]"}},"taskInfo":{"name":"for-loop-2"}}'
          - name: task-name
            value: for-loop-2
        name: iteration-driver
        template: system-dag-driver
      - arguments:
          parameters:
          - name: parent-dag-id
            value: '{{tasks.iteration-driver.outputs.parameters.execution-id}}'
          - name: iteration-index
            value: '{{item}}'
        depends: iteration-driver.Succeeded
        name: iteration-iterations
        template: comp-for-loop-2-iteration
        withSequence:
          count: '{{tasks.iteration-driver.outputs.parameters.iteration-count}}'
    inputs:
      parameters:
      - name: parent-dag-id
    metadata: {}
    name: comp-for-loop-2-for-loop-2-iterator
    outputs: {}
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: component
            value: '{{workflow.parameters.components-98f254581598234b59377784d6cbf209de79e0bcda8013fe4c4397b5d3a26767}}'
          - name: task
            value: '{"cachingOptions":{"enableCache":true},"componentRef":{"name":"comp-createpvc"},"inputs":{"parameters":{"access_modes":{"runtimeValue":{"constant":["ReadWriteOnce"]}},"pvc_name_suffix":{"runtimeValue":{"constant":"-my-pvc"}},"size":{"runtimeValue":{"constant":"5Mi"}},"storage_class_name":{"runtimeValue":{"constant":"standard"}}}},"taskInfo":{"name":"createpvc"}}'
          - name: container
            value: '{{workflow.parameters.implementations-98f254581598234b59377784d6cbf209de79e0bcda8013fe4c4397b5d3a26767}}'
          - name: task-name
            value: createpvc
          - name: parent-dag-id
            value: '{{inputs.parameters.parent-dag-id}}'
        name: createpvc
        template: system-container-driver
      - arguments:
          parameters:
          - name: parent-dag-id
            value: '{{inputs.parameters.parent-dag-id}}'
        depends: createpvc.Succeeded
        name: for-loop-2
        template: comp-for-loop-2-for-loop-2-iterator
    inputs:
      parameters:
      - name: parent-dag-id
    metadata: {}
    name: root
    outputs: {}
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: component
            value: '{{workflow.parameters.components-root}}'
          - name: runtime-config
            value: '{"parameterValues":{"my_pvc_name_suffix":"test-pvc"}}'
          - name: driver-type
            value: ROOT_DAG
        name: root-driver
        template: system-dag-driver
      - arguments:
          parameters:
          - name: parent-dag-id
            value: '{{tasks.root-driver.outputs.parameters.execution-id}}'
          - name: condition
            value: ""
        depends: root-driver.Succeeded
        name: root
        template: root
    inputs: {}
    metadata: {}
    name: entrypoint
    outputs: {}
status:
  finishedAt: null
  startedAt: null
