apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipeline-with-importer-retry-
spec:
  arguments:
    parameters:
    - name: components-comp-importer
      value: '{"executorLabel":"exec-importer","inputDefinitions":{"parameters":{"uri":{"parameterType":"STRING"}}},"outputDefinitions":{"artifacts":{"artifact":{"artifactType":{"schemaTitle":"system.Dataset","schemaVersion":"0.0.1"}}}}}'
    - name: implementations-comp-importer
      value: '{"artifactUri":{"constant":"gs://ml-pipeline-playground/shakespeare1.txt"},"typeSchema":{"schemaTitle":"system.Dataset","schemaVersion":"0.0.1"}}'
    - name: components-root
      value: '{"dag":{"tasks":{"importer":{"cachingOptions":{"enableCache":true},"componentRef":{"name":"comp-importer"},"inputs":{"parameters":{"uri":{"runtimeValue":{"constant":"gs://ml-pipeline-playground/shakespeare1.txt"}}}},"retryPolicy":{"backoffDuration":"10s","backoffFactor":2,"backoffMaxDuration":"60s","maxRetryCount":3},"taskInfo":{"name":"importer"}}}}}'
  entrypoint: entrypoint
  podMetadata:
    annotations:
      pipelines.kubeflow.org/v2_component: "true"
    labels:
      pipelines.kubeflow.org/v2_component: "true"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: pipeline-runner
  templates:
  - container:
      args:
      - --executor_type
      - importer
      - --task_spec
      - '{{inputs.parameters.task}}'
      - --component_spec
      - '{{inputs.parameters.component}}'
      - --importer_spec
      - '{{inputs.parameters.importer}}'
      - --pipeline_name
      - pipeline-with-importer-retry
      - --run_id
      - '{{workflow.uid}}'
      - --parent_dag_id
      - '{{inputs.parameters.parent-dag-id}}'
      - --pod_name
      - $(KFP_POD_NAME)
      - --pod_uid
      - $(KFP_POD_UID)
      - --mlmd_server_address
      - metadata-grpc-service.kubeflow.svc.cluster.local
      - --mlmd_server_port
      - "8080"
      - --cache_disabled=false
      - --ml_pipeline_tls_enabled=false
      - --metadata_tls_enabled=false
      - --ca_cert_path
      - ""
      - --log_level
      - "1"
      - --publish_logs
      - "true"
      command:
      - launcher-v2
      env:
      - name: KFP_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: KFP_POD_UID
        valueFrom:
          fieldRef:
            fieldPath: metadata.uid
      envFrom:
      - configMapRef:
          name: metadata-grpc-configmap
          optional: true
      image: ghcr.io/kubeflow/kfp-launcher:latest
      name: ""
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    inputs:
      parameters:
      - name: task
      - name: component
      - name: importer
      - name: parent-dag-id
      - name: retry-max-count
      - name: retry-backoff-duration
      - name: retry-backoff-factor
      - name: retry-backoff-max-duration
    metadata:
      annotations:
        pipelines.kubeflow.org/runtime-role: launcher
    name: retry-system-importer
    outputs: {}
    retryStrategy:
      backoff:
        duration: '{{inputs.parameters.retry-backoff-duration}}'
        factor: '{{inputs.parameters.retry-backoff-factor}}'
        maxDuration: '{{inputs.parameters.retry-backoff-max-duration}}'
      limit: '{{inputs.parameters.retry-max-count}}'
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: task
            value: '{"cachingOptions":{"enableCache":true},"componentRef":{"name":"comp-importer"},"inputs":{"parameters":{"uri":{"runtimeValue":{"constant":"gs://ml-pipeline-playground/shakespeare1.txt"}}}},"retryPolicy":{"backoffDuration":"10s","backoffFactor":2,"backoffMaxDuration":"60s","maxRetryCount":3},"taskInfo":{"name":"importer"}}'
          - name: component
            value: '{{workflow.parameters.components-comp-importer}}'
          - name: importer
            value: '{{workflow.parameters.implementations-comp-importer}}'
          - name: parent-dag-id
            value: '{{inputs.parameters.parent-dag-id}}'
          - name: retry-max-count
            value: "3"
          - name: retry-backoff-duration
            value: "10"
          - name: retry-backoff-factor
            value: "2"
          - name: retry-backoff-max-duration
            value: "60"
        name: importer
        template: retry-system-importer
    inputs:
      parameters:
      - name: parent-dag-id
    metadata: {}
    name: root
    outputs: {}
  - container:
      args:
      - --type
      - '{{inputs.parameters.driver-type}}'
      - --pipeline_name
      - pipeline-with-importer-retry
      - --run_id
      - '{{workflow.uid}}'
      - --run_name
      - '{{workflow.name}}'
      - --run_display_name
      - ""
      - --pipeline_job_create_time_utc
      - '{{workflow.creationTimestamp}}'
      - --dag_execution_id
      - '{{inputs.parameters.parent-dag-id}}'
      - --component
      - '{{inputs.parameters.component}}'
      - --task
      - '{{inputs.parameters.task}}'
      - --task_name
      - '{{inputs.parameters.task-name}}'
      - --runtime_config
      - '{{inputs.parameters.runtime-config}}'
      - --iteration_index
      - '{{inputs.parameters.iteration-index}}'
      - --execution_id_path
      - '{{outputs.parameters.execution-id.path}}'
      - --iteration_count_path
      - '{{outputs.parameters.iteration-count.path}}'
      - --condition_path
      - '{{outputs.parameters.condition.path}}'
      - --http_proxy
      - ""
      - --https_proxy
      - ""
      - --no_proxy
      - ""
      - --ml_pipeline_server_address
      - ml-pipeline.kubeflow.svc.cluster.local
      - --ml_pipeline_server_port
      - "8887"
      - --mlmd_server_address
      - metadata-grpc-service.kubeflow.svc.cluster.local
      - --mlmd_server_port
      - "8080"
      - --cache_disabled=false
      - --log_level
      - "1"
      - --publish_logs
      - "true"
      - --ml_pipeline_tls_enabled=false
      - --metadata_tls_enabled=false
      - --ca_cert_path
      - ""
      command:
      - driver
      image: ghcr.io/kubeflow/kfp-driver:latest
      name: ""
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    inputs:
      parameters:
      - name: component
      - default: ""
        name: runtime-config
      - default: ""
        name: task
      - default: ""
        name: task-name
      - default: "0"
        name: parent-dag-id
      - default: "-1"
        name: iteration-index
      - default: DAG
        name: driver-type
    metadata:
      annotations:
        pipelines.kubeflow.org/runtime-role: driver
    name: system-dag-driver
    outputs:
      parameters:
      - name: execution-id
        valueFrom:
          path: /tmp/outputs/execution-id
      - name: iteration-count
        valueFrom:
          default: "0"
          path: /tmp/outputs/iteration-count
      - name: condition
        valueFrom:
          default: "true"
          path: /tmp/outputs/condition
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: component
            value: '{{workflow.parameters.components-root}}'
          - name: runtime-config
            value: '{}'
          - name: driver-type
            value: ROOT_DAG
        name: root-driver
        template: system-dag-driver
      - arguments:
          parameters:
          - name: parent-dag-id
            value: '{{tasks.root-driver.outputs.parameters.execution-id}}'
          - name: condition
            value: ""
        depends: root-driver.Succeeded
        name: root
        template: root
    inputs: {}
    metadata: {}
    name: entrypoint
    outputs: {}
status:
  finishedAt: null
  startedAt: null
