# proto-file: third_party/py/google_cloud_pipeline_components/templates_in_gallery/protos/gallery_metadata.proto
# proto-message: GalleryMetadata

# Forked from google3/third_party/py/google_cloud_pipeline_components/templates_in_gallery/protos/gallery_metadata_sample.textproto
upload_template_request {
  vertex_template_gallery_metadata {
    vertex_gallery_categorization {
      type: COMPONENT
      integration: BIG_QUERY
    }
    display_name: "BigQuery - Explain Forecast Model Component"
  }
  description: "Generates forecasts based on a trained time-series model, such as the ARIMA_PLUS or ARIMA_PLUS_XREG model."
}

# Which python function defines the pipeline.
pipeline_func: "google_cloud_pipeline_components.v1.bigquery.explain_forecast_model.BigqueryExplainForecastModelJobOp"