apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../pipeline
- ../../cache
- ../../cache-deployer
- pipeline-install-config.yaml
- mysql-secret.yaml
configurations:
- params.yaml
replacements:
- source:
    kind: Deployment
    name: ml-pipeline
    fieldPath: metadata.namespace
  targets:
  - select:
      kind: MutatingWebhookConfiguration
      name: pipelineversions.pipelines.kubeflow.org
    fieldPaths:
    - webhooks.*.clientConfig.service.namespace
  - select:
      kind: ValidatingWebhookConfiguration
      name: pipelineversions.pipelines.kubeflow.org
    fieldPaths:
    - webhooks.*.clientConfig.service.namespace
  - select:
      kind: MutatingWebhookConfiguration
      name: cache-webhook-kubeflow
    fieldPaths:
    - webhooks.*.clientConfig.service.namespace
- source:
    fieldPath: data.appName
    kind: ConfigMap
    name: pipeline-install-config
    version: v1
  targets:
  - select:
      kind: Application
    fieldPaths:
    - metadata.name
- source:
    fieldPath: data.appVersion
    kind: ConfigMap
    name: pipeline-install-config
    version: v1
  targets:
    - select:
        kind: Application
      fieldPaths:
      - spec.descriptor.version
- source:
    fieldPath: data.bucketName
    kind: ConfigMap
    name: pipeline-install-config
    version: v1
  targets:
  - select:
      kind: ConfigMap
      name: workflow-controller-configmap
    fieldPaths:
    - data.artifactRepository.s3.bucket

