apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- ../../pipeline
- ../../cache
- ../../cache-deployer
- pipeline-install-config.yaml
- mysql-secret.yaml

replacements:
- source:
    kind: Deployment
    name: ml-pipeline
    fieldPath: metadata.namespace
  targets:
  - select:
      name: kfp-namespace

- source:
    kind: ConfigMap
    name: pipeline-install-config
    fieldPath: data.appName
  targets:
  - select:
      name: kfp-app-name

- source:
    kind: ConfigMap
    name: pipeline-install-config
    fieldPath: data.appVersion
  targets:
  - select:
      name: kfp-app-version

- source:
    kind: ConfigMap
    name: pipeline-install-config
    fieldPath: data.bucketName
  targets:
  - select:
      name: kfp-artifact-bucket-name

- source:
    kind: ConfigMap
    name: pipeline-install-config
    fieldPath: data.defaultPipelineRoot
  targets:
  - select:
      name: kfp-default-pipeline-root

configurations:
- params.yaml
