FROM golang:1.10


# Download and install the latest release of dep
ADD https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep

WORKDIR /go/src/github.com/googleprivate/ml/backend
COPY . .

WORKDIR /go/src/github.com/googleprivate/ml/backend/src
RUN dep ensure --vendor-only
RUN go build -o /bin/persistence_agent ./agent/persistence/*.go


FROM ubuntu
WORKDIR /bin

COPY --from=0 /bin/persistence_agent /bin/persistence_agent
RUN chmod +x /bin/persistence_agent

CMD persistence_agent \
  --alsologtostderr=true
