apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/crds
- ../../platform-agnostic-multi-user
- ../base-tls-certs/

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.

# !!! If you want to customize the namespace,
# please also update base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml
namespace: kubeflow
labels:
- includeSelectors: true
  pairs:
    application-crd-id: kubeflow-pipelines

patches:
  - path: patches/deployment.yaml
    target:
      kind: Deployment
      name: ml-pipeline
