apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kfp-cache-cert
spec:
  commonName: kfp-cache-cert
  isCA: true
  dnsNames:
  - cache-server
  issuerRef:
    kind: Issuer
    name: kfp-cache-selfsigned-issuer
  secretName: webhook-server-tls