// Code generated by go-swagger; DO NOT EDIT.

package run_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTerminateRunV1Params creates a new TerminateRunV1Params object
// with the default values initialized.
func NewTerminateRunV1Params() *TerminateRunV1Params {
	var ()
	return &TerminateRunV1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewTerminateRunV1ParamsWithTimeout creates a new TerminateRunV1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewTerminateRunV1ParamsWithTimeout(timeout time.Duration) *TerminateRunV1Params {
	var ()
	return &TerminateRunV1Params{

		timeout: timeout,
	}
}

// NewTerminateRunV1ParamsWithContext creates a new TerminateRunV1Params object
// with the default values initialized, and the ability to set a context for a request
func NewTerminateRunV1ParamsWithContext(ctx context.Context) *TerminateRunV1Params {
	var ()
	return &TerminateRunV1Params{

		Context: ctx,
	}
}

// NewTerminateRunV1ParamsWithHTTPClient creates a new TerminateRunV1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTerminateRunV1ParamsWithHTTPClient(client *http.Client) *TerminateRunV1Params {
	var ()
	return &TerminateRunV1Params{
		HTTPClient: client,
	}
}

/*TerminateRunV1Params contains all the parameters to send to the API endpoint
for the terminate run v1 operation typically these are written to a http.Request
*/
type TerminateRunV1Params struct {

	/*RunID
	  The ID of the run to be terminated.

	*/
	RunID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the terminate run v1 params
func (o *TerminateRunV1Params) WithTimeout(timeout time.Duration) *TerminateRunV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the terminate run v1 params
func (o *TerminateRunV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the terminate run v1 params
func (o *TerminateRunV1Params) WithContext(ctx context.Context) *TerminateRunV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the terminate run v1 params
func (o *TerminateRunV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the terminate run v1 params
func (o *TerminateRunV1Params) WithHTTPClient(client *http.Client) *TerminateRunV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the terminate run v1 params
func (o *TerminateRunV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRunID adds the runID to the terminate run v1 params
func (o *TerminateRunV1Params) WithRunID(runID string) *TerminateRunV1Params {
	o.SetRunID(runID)
	return o
}

// SetRunID adds the runId to the terminate run v1 params
func (o *TerminateRunV1Params) SetRunID(runID string) {
	o.RunID = runID
}

// WriteToRequest writes these params to a swagger request
func (o *TerminateRunV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param run_id
	if err := r.SetPathParam("run_id", o.RunID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
