// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubeflow/pipelines/backend/src/crd/pkg/apis/viewer/v1alpha1"
	scheme "github.com/kubeflow/pipelines/backend/src/crd/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ViewersGetter has a method to return a ViewerInterface.
// A group's client should implement this interface.
type ViewersGetter interface {
	Viewers(namespace string) ViewerInterface
}

// ViewerInterface has methods to work with Viewer resources.
type ViewerInterface interface {
	Create(*v1alpha1.Viewer) (*v1alpha1.Viewer, error)
	Update(*v1alpha1.Viewer) (*v1alpha1.Viewer, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Viewer, error)
	List(opts v1.ListOptions) (*v1alpha1.ViewerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Viewer, err error)
	ViewerExpansion
}

// viewers implements ViewerInterface
type viewers struct {
	client rest.Interface
	ns     string
}

// newViewers returns a Viewers
func newViewers(c *ViewerV1alpha1Client, namespace string) *viewers {
	return &viewers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the viewer, and returns the corresponding viewer object, and an error if there is any.
func (c *viewers) Get(name string, options v1.GetOptions) (result *v1alpha1.Viewer, err error) {
	result = &v1alpha1.Viewer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("viewers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Viewers that match those selectors.
func (c *viewers) List(opts v1.ListOptions) (result *v1alpha1.ViewerList, err error) {
	result = &v1alpha1.ViewerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("viewers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested viewers.
func (c *viewers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("viewers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a viewer and creates it.  Returns the server's representation of the viewer, and an error, if there is any.
func (c *viewers) Create(viewer *v1alpha1.Viewer) (result *v1alpha1.Viewer, err error) {
	result = &v1alpha1.Viewer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("viewers").
		Body(viewer).
		Do().
		Into(result)
	return
}

// Update takes the representation of a viewer and updates it. Returns the server's representation of the viewer, and an error, if there is any.
func (c *viewers) Update(viewer *v1alpha1.Viewer) (result *v1alpha1.Viewer, err error) {
	result = &v1alpha1.Viewer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("viewers").
		Name(viewer.Name).
		Body(viewer).
		Do().
		Into(result)
	return
}

// Delete takes name of the viewer and deletes it. Returns an error if one occurs.
func (c *viewers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("viewers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *viewers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("viewers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched viewer.
func (c *viewers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Viewer, err error) {
	result = &v1alpha1.Viewer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("viewers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
