apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: TrainingJob
metadata:
  name:
  annotations:
    services.k8s.aws/region:
spec:
  algorithmSpecification: 
  checkpointConfig: 
  debugHookConfig: 
  debugRuleConfigurations: 
  enableInterContainerTrafficEncryption: 
  enableManagedSpotTraining: 
  enableNetworkIsolation: 
  environment: 
  experimentConfig: 
  hyperParameters: 
  inputDataConfig: 
  outputDataConfig: 
  profilerConfig: 
  profilerRuleConfigurations: 
  resourceConfig: 
  retryStrategy: 
  roleARN: 
  stoppingCondition: 
  tags: 
  tensorBoardOutputConfig: 
  trainingJobName: 
  vpcConfig: 
