[tox]
envlist = py27, py3
skip_missing_interpreters = true

[testenv]
deps=
     certifi
     six >= 1.10
     python-dateutil
     urllib3 >= 1.15
     -rtest-requirements.txt

commands=
   pytest --cov=kfp_server_api
