[tox]
envlist = py27, py3

[testenv]
deps=
     certifi
     six >= 1.10
     python-dateutil
     urllib3 >= 1.15
     pytest~=4.6.7
     pytest-cov>=2.8.1
     pytest-randomly==1.2.3

commands=
   pytest --cov=kfp_server_api
