[tox]
envlist = py311, py312, py313, py314
skip_missing_interpreters = true

[testenv]
deps=
     -r{toxinidir}/requirements.txt
     -r{toxinidir}/test-requirements.txt

commands=
   pytest --cov=kfp_server_api
