apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs
spec:
  template:
    spec:
      containers:
        - name: seaweedfs
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              memory: 1Gi
