BUILT_IN_ALGOS = {
    "blazingtext": "blazingtext",
    "deepar forecasting": "forecasting-deepar",
    "factorization machines": "factorization-machines",
    "image classification": "image-classification",
    "ip insights": "ipinsights",
    "k-means": "kmeans",
    "k-nearest neighbors": "knn",
    "k-nn": "knn",
    "lda": "lda",
    "linear learner": "linear-learner",
    "neural topic model": "ntm",
    "object2vec": "object2vec",
    "object detection": "object-detection",
    "pca": "pca",
    "random cut forest": "randomcutforest",
    "semantic segmentation": "semantic-segmentation",
    "sequence to sequence": "seq2seq",
    "seq2seq modeling": "seq2seq",
    "xgboost": "xgboost",
}