name: "Build and install the unified KFP SDK"
description: "Generate Python bindings before building and installing kfp"
inputs:
  build_version:
    required: true
    default: "1.3.0"
    description: "build package version"
  generate_golang_proto:
    required: true
    default: "false"
    description: "optionally generate golang proto files"
runs:
  using: "composite"
  steps:
    - name: Generate bindings and build kfp
      id: install-kfp
      shell: bash
      run: |
        rm -rf sdk/python/dist/
        make -C sdk python
        uv pip install --reinstall sdk/python/dist/*.whl

    - name: Generate kfp-kubernetes golang proto files from source
      id: generate-kfp-kubernetes-go-proto-files
      shell: bash
      if: ${{ inputs.generate_golang_proto == 'true' }}
      working-directory: ./kubernetes_platform
      run: make golang

    # testing reinstalling kfp package from source with no deps
    - name: Reinstall kfp from source with no deps
      id: reinstall-kfp
      shell: bash
      working-directory: ./sdk/python
      run: |
        uv pip install . --reinstall --no-deps
