apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- pipelineversion-validating-webhook-config.yaml
- pipelineversion-mutating-webhook-config.yaml

configMapGenerator:
- name: kfp-webhook-params
  literals:
  - namespace=kubeflow

replacements:
- source:
    kind: ConfigMap
    name: kfp-webhook-params
    fieldPath: data.namespace
  targets:
  - select:
      kind: MutatingWebhookConfiguration
      name: pipelineversions.pipelines.kubeflow.org
    fieldPaths:
    - webhooks.0.clientConfig.service.namespace
  - select:
      kind: ValidatingWebhookConfiguration
      name: pipelineversions.pipelines.kubeflow.org
    fieldPaths:
    - webhooks.0.clientConfig.service.namespace
