// Code generated by go-swagger; DO NOT EDIT.

package package_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListPackagesParams creates a new ListPackagesParams object
// with the default values initialized.
func NewListPackagesParams() *ListPackagesParams {
	var ()
	return &ListPackagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListPackagesParamsWithTimeout creates a new ListPackagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListPackagesParamsWithTimeout(timeout time.Duration) *ListPackagesParams {
	var ()
	return &ListPackagesParams{

		timeout: timeout,
	}
}

// NewListPackagesParamsWithContext creates a new ListPackagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListPackagesParamsWithContext(ctx context.Context) *ListPackagesParams {
	var ()
	return &ListPackagesParams{

		Context: ctx,
	}
}

// NewListPackagesParamsWithHTTPClient creates a new ListPackagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListPackagesParamsWithHTTPClient(client *http.Client) *ListPackagesParams {
	var ()
	return &ListPackagesParams{
		HTTPClient: client,
	}
}

/*ListPackagesParams contains all the parameters to send to the API endpoint
for the list packages operation typically these are written to a http.Request
*/
type ListPackagesParams struct {

	/*PageSize*/
	PageSize *int32
	/*PageToken*/
	PageToken *string
	/*SortBy*/
	SortBy *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list packages params
func (o *ListPackagesParams) WithTimeout(timeout time.Duration) *ListPackagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list packages params
func (o *ListPackagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list packages params
func (o *ListPackagesParams) WithContext(ctx context.Context) *ListPackagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list packages params
func (o *ListPackagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list packages params
func (o *ListPackagesParams) WithHTTPClient(client *http.Client) *ListPackagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list packages params
func (o *ListPackagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPageSize adds the pageSize to the list packages params
func (o *ListPackagesParams) WithPageSize(pageSize *int32) *ListPackagesParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the list packages params
func (o *ListPackagesParams) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WithPageToken adds the pageToken to the list packages params
func (o *ListPackagesParams) WithPageToken(pageToken *string) *ListPackagesParams {
	o.SetPageToken(pageToken)
	return o
}

// SetPageToken adds the pageToken to the list packages params
func (o *ListPackagesParams) SetPageToken(pageToken *string) {
	o.PageToken = pageToken
}

// WithSortBy adds the sortBy to the list packages params
func (o *ListPackagesParams) WithSortBy(sortBy *string) *ListPackagesParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the list packages params
func (o *ListPackagesParams) SetSortBy(sortBy *string) {
	o.SortBy = sortBy
}

// WriteToRequest writes these params to a swagger request
func (o *ListPackagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int32
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {
			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}

	}

	if o.PageToken != nil {

		// query param page_token
		var qrPageToken string
		if o.PageToken != nil {
			qrPageToken = *o.PageToken
		}
		qPageToken := qrPageToken
		if qPageToken != "" {
			if err := r.SetQueryParam("page_token", qPageToken); err != nil {
				return err
			}
		}

	}

	if o.SortBy != nil {

		// query param sort_by
		var qrSortBy string
		if o.SortBy != nil {
			qrSortBy = *o.SortBy
		}
		qSortBy := qrSortBy
		if qSortBy != "" {
			if err := r.SetQueryParam("sort_by", qSortBy); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
