#!/usr/bin/env python3
# Copyright 2026 The Kubeflow Authors
# Licensed under the Apache License, Version 2.0.
"""Generate legacy Python model imports as aliases of the canonical v2 models."""

from pathlib import Path
import re
import sys


def generate(client_root: Path) -> None:
    """Keep both top-level and module-qualified v2beta1 imports working."""
    aliases = []
    header = '# Generated by backend/api/hack/generate_python_compat.py. Do not edit.\n'
    for model in sorted((client_root / 'models').glob('v2_*.py')):
        source = model.read_text()
        match = re.search(r'^class (V2\w+)\(', source, re.MULTILINE)
        if not match:
            raise ValueError(f'No canonical model class found in {model}')
        canonical = match.group(1)
        legacy = canonical.replace('V2', 'V2beta1', 1)
        alias = (f'from kfp.server_api.models.{model.stem} import '
                 f'{canonical} as {legacy}\n')
        model.with_name(model.name.replace('v2_', 'v2beta1_',
                                           1)).write_text(header + alias)
        aliases.append(alias)
    for initializer in (client_root / '__init__.py',
                        client_root / 'models' / '__init__.py'):
        with initializer.open('a') as output:
            output.write('\n' + header + ''.join(aliases))


if __name__ == '__main__':
    generate(Path(sys.argv[1]))
