/* tslint:disable */
/* eslint-disable */
/**
 * backend/api/v2beta1/run.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V2beta1PipelineTask } from './V2beta1PipelineTask';
import {
  V2beta1PipelineTaskFromJSON,
  V2beta1PipelineTaskFromJSONTyped,
  V2beta1PipelineTaskToJSON,
  V2beta1PipelineTaskToJSONTyped,
} from './V2beta1PipelineTask';

/**
 *
 * @export
 * @interface V2beta1FindCachedTaskResponse
 */
export interface V2beta1FindCachedTaskResponse {
  /**
   *
   * @type {V2beta1PipelineTask}
   * @memberof V2beta1FindCachedTaskResponse
   */
  task?: V2beta1PipelineTask;
}

/**
 * Check if a given object implements the V2beta1FindCachedTaskResponse interface.
 */
export function instanceOfV2beta1FindCachedTaskResponse(
  value: object,
): value is V2beta1FindCachedTaskResponse {
  return true;
}

export function V2beta1FindCachedTaskResponseFromJSON(json: any): V2beta1FindCachedTaskResponse {
  return V2beta1FindCachedTaskResponseFromJSONTyped(json, false);
}

export function V2beta1FindCachedTaskResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): V2beta1FindCachedTaskResponse {
  if (json == null) {
    return json;
  }
  return {
    task: json['task'] == null ? undefined : V2beta1PipelineTaskFromJSON(json['task']),
  };
}

export function V2beta1FindCachedTaskResponseToJSON(json: any): V2beta1FindCachedTaskResponse {
  return V2beta1FindCachedTaskResponseToJSONTyped(json, false);
}

export function V2beta1FindCachedTaskResponseToJSONTyped(
  value?: V2beta1FindCachedTaskResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    task: V2beta1PipelineTaskToJSON(value['task']),
  };
}
