// Code generated by go-swagger; DO NOT EDIT.

package artifact_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V2beta1ListArtifactTasksResponse v2beta1 list artifact tasks response
//
// swagger:model v2beta1ListArtifactTasksResponse
type V2beta1ListArtifactTasksResponse struct {

	// artifact tasks
	ArtifactTasks []*V2beta1ArtifactTask `json:"artifact_tasks"`

	// next page token
	NextPageToken string `json:"next_page_token,omitempty"`

	// total size
	TotalSize int32 `json:"total_size,omitempty"`
}

// Validate validates this v2beta1 list artifact tasks response
func (m *V2beta1ListArtifactTasksResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArtifactTasks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V2beta1ListArtifactTasksResponse) validateArtifactTasks(formats strfmt.Registry) error {
	if swag.IsZero(m.ArtifactTasks) { // not required
		return nil
	}

	for i := 0; i < len(m.ArtifactTasks); i++ {
		if swag.IsZero(m.ArtifactTasks[i]) { // not required
			continue
		}

		if m.ArtifactTasks[i] != nil {
			if err := m.ArtifactTasks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("artifact_tasks" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("artifact_tasks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v2beta1 list artifact tasks response based on the context it is used
func (m *V2beta1ListArtifactTasksResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateArtifactTasks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V2beta1ListArtifactTasksResponse) contextValidateArtifactTasks(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ArtifactTasks); i++ {

		if m.ArtifactTasks[i] != nil {

			if swag.IsZero(m.ArtifactTasks[i]) { // not required
				return nil
			}

			if err := m.ArtifactTasks[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("artifact_tasks" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("artifact_tasks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V2beta1ListArtifactTasksResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V2beta1ListArtifactTasksResponse) UnmarshalBinary(b []byte) error {
	var res V2beta1ListArtifactTasksResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
