apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../manifests/kustomize/env/platform-agnostic-multi-user
  - ../../base

images:
  - name: ghcr.io/kubeflow/kfp-api-server
    newName: kind-registry:5000/apiserver
    newTag: latest
  - name: ghcr.io/kubeflow/kfp-persistence-agent
    newName: kind-registry:5000/persistenceagent
    newTag: latest
  - name: ghcr.io/kubeflow/kfp-scheduled-workflow-controller
    newName: kind-registry:5000/scheduledworkflow
    newTag: latest
  - name: ghcr.io/kubeflow/kfp-frontend
    newName: kind-registry:5000/frontend
    newTag: latest
  - name: ghcr.io/kubeflow/kfp-viewer-crd-controller
    newName: kind-registry:5000/viewer-crd-controller
    newTag: latest
patches:
  - path: ../pipeline-crd-rbac.yaml
    target:
      kind: ClusterRole
      name: ml-pipeline
  - path: ../../base/apiserver-env.yaml
    target:
      kind: Deployment
      name: ml-pipeline
  - path: ../../base/ci-stability-tuning.yaml
  - path: ../../base/driver-plugin-cm-path.yaml
    target:
      kind: ConfigMap
      name: ml-pipeline-driver-agent
  - path: ../../base/viewer-crd-pull-policy.yaml
    target:
      kind: Deployment
      name: ml-pipeline-viewer-crd
  - path: env.yaml
    target:
      kind: Deployment
      name: kubeflow-pipelines-profile-controller
  - target:
      kind: ConfigMap
      name: pipeline-install-config
    patch: |
      - op: add
        path: /data/ARTIFACTS_PROXY_ENABLED
        value: "true"
  - target:
      kind: Deployment
      name: kubeflow-pipelines-profile-controller
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DISABLE_ISTIO_SIDECAR
          value: "true" # Dangerous and only for CI/CD, not production usage

replacements:
  - source:
      kind: ConfigMap
      name: dns-config
      fieldPath: data.namespaceDns
    targets:
      - select:
          kind: Deployment
          name: ml-pipeline
        fieldPaths:
          - spec.template.spec.dnsConfig.searches.[=NAMESPACE.svc.cluster.local]
