// Code generated by go-swagger; DO NOT EDIT.

package job_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	job_model "github.com/kubeflow/pipelines/backend/api/v1beta1/go_http_client/job_model"
)

// JobServiceEnableJobReader is a Reader for the JobServiceEnableJob structure.
type JobServiceEnableJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobServiceEnableJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewJobServiceEnableJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewJobServiceEnableJobDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewJobServiceEnableJobOK creates a JobServiceEnableJobOK with default headers values
func NewJobServiceEnableJobOK() *JobServiceEnableJobOK {
	return &JobServiceEnableJobOK{}
}

/*JobServiceEnableJobOK handles this case with default header values.

A successful response.
*/
type JobServiceEnableJobOK struct {
	Payload interface{}
}

func (o *JobServiceEnableJobOK) Error() string {
	return fmt.Sprintf("[POST /apis/v1beta1/jobs/{id}/enable][%d] jobServiceEnableJobOK  %+v", 200, o.Payload)
}

func (o *JobServiceEnableJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJobServiceEnableJobDefault creates a JobServiceEnableJobDefault with default headers values
func NewJobServiceEnableJobDefault(code int) *JobServiceEnableJobDefault {
	return &JobServiceEnableJobDefault{
		_statusCode: code,
	}
}

/*JobServiceEnableJobDefault handles this case with default header values.

An unexpected error response.
*/
type JobServiceEnableJobDefault struct {
	_statusCode int

	Payload *job_model.GatewayruntimeError
}

// Code gets the status code for the job service enable job default response
func (o *JobServiceEnableJobDefault) Code() int {
	return o._statusCode
}

func (o *JobServiceEnableJobDefault) Error() string {
	return fmt.Sprintf("[POST /apis/v1beta1/jobs/{id}/enable][%d] JobService_EnableJob default  %+v", o._statusCode, o.Payload)
}

func (o *JobServiceEnableJobDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(job_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
