apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-api-server
          readinessProbe:
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            timeoutSeconds: 5
            failureThreshold: 6
          startupProbe:
            failureThreshold: 24
            timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: seaweedfs
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
