name: "Set up Go"
description: "Sets up Go"
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
      with:
        go-version-file: go.mod
