apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../../postgresql/pipeline
- ../../../postgresql/cache
- ../../../cache-deployer
- pipeline-install-config.yaml
- postgres-secret-extended.yaml
replacements:
- source:
    kind: ConfigMap
    name: pipeline-install-config
    fieldPath: data.defaultPipelineRoot
  targets:
  - select:
      kind: ConfigMap
      name: kfp-launcher
    fieldPaths:
    - data.defaultPipelineRoot
