apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
- namespace.yaml
- ../third-party/application/cluster-scoped
- ../third-party/argo/installs/namespace/cluster-scoped
- ../base/pipeline/cluster-scoped
- ../base/cache-deployer/cluster-scoped

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: kfp-cluster-scoped-params
  literals:
  - namespace=kubeflow

replacements:
- source:
    kind: ConfigMap
    name: kfp-cluster-scoped-params
    fieldPath: data.namespace
  targets:
  - select:
      kind: Namespace
    fieldPaths:
    - metadata.name
