apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-server
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: server
          args:
            - --db_driver=$(DBCONFIG_DRIVER)
            - --db_host=$(DBCONFIG_HOST_NAME)
            - --db_port=$(DBCONFIG_PORT)
            - --db_name=$(DBCONFIG_DB_NAME)
            - --db_user=$(DBCONFIG_USER)
            - --db_password=$(DBCONFIG_PASSWORD)
            - --db_extra_params={"tls":"false"}
            - --namespace_to_watch=$(NAMESPACE_TO_WATCH)
            - --listen_port=$(WEBHOOK_PORT)
