apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  namespace: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
        - name: squid
          image: registry.domain.local/squid:test
          ports:
            - containerPort: 3128
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
          startupProbe:
            tcpSocket:
              port: 3128
            periodSeconds: 2
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 3128
            periodSeconds: 2
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 3128
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: squid-cache
              mountPath: /var/cache/squid
            - name: squid-log
              mountPath: /var/log/squid
      volumes:
        - name: squid-cache
          emptyDir: { }
        - name: squid-log
          emptyDir: { }
