FROM registry.access.redhat.com/ubi9/nginx-124

EXPOSE 9443

ADD webhook-proxy-nginx.conf "${NGINX_CONF_PATH}"

# Run script uses standard ways to run the application
CMD ["nginx", "-g", "daemon off;"]
