apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline
  namespace: {{ .Release.Namespace }}
  labels:
    app: ml-pipeline
spec:
  ports:
    - name: http
      port: 8888
      targetPort: http
    - name: grpc
      port: 8887
      targetPort: grpc
  selector:
    app: ml-pipeline
