apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-api-server
        envFrom:
        - configMapRef:
            name: pipeline-api-server-config
        env:
        - name: KUBEFLOW_USERID_HEADER
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: USERID_HEADER
              optional: true
        - name: KUBEFLOW_USERID_PREFIX
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: USERID_PREFIX
              optional: true
