/* tslint:disable */
/* eslint-disable */
/**
 * backend/api/v2/pipeline.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V2Pipeline } from './V2Pipeline';
import {
  V2PipelineFromJSON,
  V2PipelineFromJSONTyped,
  V2PipelineToJSON,
  V2PipelineToJSONTyped,
} from './V2Pipeline';

/**
 *
 * @export
 * @interface V2ListPipelinesResponse
 */
export interface V2ListPipelinesResponse {
  /**
   * Returned pipelines.
   * @type {Array<V2Pipeline>}
   * @memberof V2ListPipelinesResponse
   */
  pipelines?: Array<V2Pipeline>;
  /**
   * The total number of pipelines for the given query.
   * @type {number}
   * @memberof V2ListPipelinesResponse
   */
  total_size?: number;
  /**
   * The token to list the next page of pipelines.
   * This token can be used on the next ListPipelinesRequest.
   * @type {string}
   * @memberof V2ListPipelinesResponse
   */
  next_page_token?: string;
}

/**
 * Check if a given object implements the V2ListPipelinesResponse interface.
 */
export function instanceOfV2ListPipelinesResponse(value: object): value is V2ListPipelinesResponse {
  return true;
}

export function V2ListPipelinesResponseFromJSON(json: any): V2ListPipelinesResponse {
  return V2ListPipelinesResponseFromJSONTyped(json, false);
}

export function V2ListPipelinesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): V2ListPipelinesResponse {
  if (json == null) {
    return json;
  }
  return {
    pipelines:
      json['pipelines'] == null
        ? undefined
        : (json['pipelines'] as Array<any>).map(V2PipelineFromJSON),
    total_size: json['total_size'] == null ? undefined : json['total_size'],
    next_page_token: json['next_page_token'] == null ? undefined : json['next_page_token'],
  };
}

export function V2ListPipelinesResponseToJSON(json: any): V2ListPipelinesResponse {
  return V2ListPipelinesResponseToJSONTyped(json, false);
}

export function V2ListPipelinesResponseToJSONTyped(
  value?: V2ListPipelinesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    pipelines:
      value['pipelines'] == null
        ? undefined
        : (value['pipelines'] as Array<any>).map(V2PipelineToJSON),
    total_size: value['total_size'],
    next_page_token: value['next_page_token'],
  };
}
