/* tslint:disable */
/* eslint-disable */
/**
 * backend/api/v2/pipeline.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V2PipelineVersion } from './V2PipelineVersion';
import {
  V2PipelineVersionFromJSON,
  V2PipelineVersionFromJSONTyped,
  V2PipelineVersionToJSON,
  V2PipelineVersionToJSONTyped,
} from './V2PipelineVersion';

/**
 *
 * @export
 * @interface V2ListPipelineVersionsResponse
 */
export interface V2ListPipelineVersionsResponse {
  /**
   * Returned pipeline versions.
   * @type {Array<V2PipelineVersion>}
   * @memberof V2ListPipelineVersionsResponse
   */
  pipeline_versions?: Array<V2PipelineVersion>;
  /**
   * The token to list the next page of pipeline versions.
   * @type {string}
   * @memberof V2ListPipelineVersionsResponse
   */
  next_page_token?: string;
  /**
   * The total number of pipeline versions for the given query.
   * @type {number}
   * @memberof V2ListPipelineVersionsResponse
   */
  total_size?: number;
}

/**
 * Check if a given object implements the V2ListPipelineVersionsResponse interface.
 */
export function instanceOfV2ListPipelineVersionsResponse(
  value: object,
): value is V2ListPipelineVersionsResponse {
  return true;
}

export function V2ListPipelineVersionsResponseFromJSON(json: any): V2ListPipelineVersionsResponse {
  return V2ListPipelineVersionsResponseFromJSONTyped(json, false);
}

export function V2ListPipelineVersionsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): V2ListPipelineVersionsResponse {
  if (json == null) {
    return json;
  }
  return {
    pipeline_versions:
      json['pipeline_versions'] == null
        ? undefined
        : (json['pipeline_versions'] as Array<any>).map(V2PipelineVersionFromJSON),
    next_page_token: json['next_page_token'] == null ? undefined : json['next_page_token'],
    total_size: json['total_size'] == null ? undefined : json['total_size'],
  };
}

export function V2ListPipelineVersionsResponseToJSON(json: any): V2ListPipelineVersionsResponse {
  return V2ListPipelineVersionsResponseToJSONTyped(json, false);
}

export function V2ListPipelineVersionsResponseToJSONTyped(
  value?: V2ListPipelineVersionsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    pipeline_versions:
      value['pipeline_versions'] == null
        ? undefined
        : (value['pipeline_versions'] as Array<any>).map(V2PipelineVersionToJSON),
    next_page_token: value['next_page_token'],
    total_size: value['total_size'],
  };
}
