// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kubeflow/pipelines/backend/api/v2beta1/go_http_client/pipeline_model"
)

// PipelineServiceGetPipelineReader is a Reader for the PipelineServiceGetPipeline structure.
type PipelineServiceGetPipelineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PipelineServiceGetPipelineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPipelineServiceGetPipelineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPipelineServiceGetPipelineDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPipelineServiceGetPipelineOK creates a PipelineServiceGetPipelineOK with default headers values
func NewPipelineServiceGetPipelineOK() *PipelineServiceGetPipelineOK {
	return &PipelineServiceGetPipelineOK{}
}

/*
PipelineServiceGetPipelineOK describes a response with status code 200, with default header values.

A successful response.
*/
type PipelineServiceGetPipelineOK struct {
	Payload *pipeline_model.V2beta1Pipeline
}

// IsSuccess returns true when this pipeline service get pipeline o k response has a 2xx status code
func (o *PipelineServiceGetPipelineOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pipeline service get pipeline o k response has a 3xx status code
func (o *PipelineServiceGetPipelineOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pipeline service get pipeline o k response has a 4xx status code
func (o *PipelineServiceGetPipelineOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pipeline service get pipeline o k response has a 5xx status code
func (o *PipelineServiceGetPipelineOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pipeline service get pipeline o k response a status code equal to that given
func (o *PipelineServiceGetPipelineOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the pipeline service get pipeline o k response
func (o *PipelineServiceGetPipelineOK) Code() int {
	return 200
}

func (o *PipelineServiceGetPipelineOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /apis/v2beta1/pipelines/{pipeline_id}][%d] pipelineServiceGetPipelineOK %s", 200, payload)
}

func (o *PipelineServiceGetPipelineOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /apis/v2beta1/pipelines/{pipeline_id}][%d] pipelineServiceGetPipelineOK %s", 200, payload)
}

func (o *PipelineServiceGetPipelineOK) GetPayload() *pipeline_model.V2beta1Pipeline {
	return o.Payload
}

func (o *PipelineServiceGetPipelineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_model.V2beta1Pipeline)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPipelineServiceGetPipelineDefault creates a PipelineServiceGetPipelineDefault with default headers values
func NewPipelineServiceGetPipelineDefault(code int) *PipelineServiceGetPipelineDefault {
	return &PipelineServiceGetPipelineDefault{
		_statusCode: code,
	}
}

/*
PipelineServiceGetPipelineDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PipelineServiceGetPipelineDefault struct {
	_statusCode int

	Payload *pipeline_model.GooglerpcStatus
}

// IsSuccess returns true when this pipeline service get pipeline default response has a 2xx status code
func (o *PipelineServiceGetPipelineDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this pipeline service get pipeline default response has a 3xx status code
func (o *PipelineServiceGetPipelineDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this pipeline service get pipeline default response has a 4xx status code
func (o *PipelineServiceGetPipelineDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this pipeline service get pipeline default response has a 5xx status code
func (o *PipelineServiceGetPipelineDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this pipeline service get pipeline default response a status code equal to that given
func (o *PipelineServiceGetPipelineDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the pipeline service get pipeline default response
func (o *PipelineServiceGetPipelineDefault) Code() int {
	return o._statusCode
}

func (o *PipelineServiceGetPipelineDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /apis/v2beta1/pipelines/{pipeline_id}][%d] PipelineService_GetPipeline default %s", o._statusCode, payload)
}

func (o *PipelineServiceGetPipelineDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /apis/v2beta1/pipelines/{pipeline_id}][%d] PipelineService_GetPipeline default %s", o._statusCode, payload)
}

func (o *PipelineServiceGetPipelineDefault) GetPayload() *pipeline_model.GooglerpcStatus {
	return o.Payload
}

func (o *PipelineServiceGetPipelineDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(pipeline_model.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
