// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPipelineServiceDeletePipelineVersionParams creates a new PipelineServiceDeletePipelineVersionParams object
// with the default values initialized.
func NewPipelineServiceDeletePipelineVersionParams() *PipelineServiceDeletePipelineVersionParams {
	var ()
	return &PipelineServiceDeletePipelineVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPipelineServiceDeletePipelineVersionParamsWithTimeout creates a new PipelineServiceDeletePipelineVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPipelineServiceDeletePipelineVersionParamsWithTimeout(timeout time.Duration) *PipelineServiceDeletePipelineVersionParams {
	var ()
	return &PipelineServiceDeletePipelineVersionParams{

		timeout: timeout,
	}
}

// NewPipelineServiceDeletePipelineVersionParamsWithContext creates a new PipelineServiceDeletePipelineVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewPipelineServiceDeletePipelineVersionParamsWithContext(ctx context.Context) *PipelineServiceDeletePipelineVersionParams {
	var ()
	return &PipelineServiceDeletePipelineVersionParams{

		Context: ctx,
	}
}

// NewPipelineServiceDeletePipelineVersionParamsWithHTTPClient creates a new PipelineServiceDeletePipelineVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPipelineServiceDeletePipelineVersionParamsWithHTTPClient(client *http.Client) *PipelineServiceDeletePipelineVersionParams {
	var ()
	return &PipelineServiceDeletePipelineVersionParams{
		HTTPClient: client,
	}
}

/*PipelineServiceDeletePipelineVersionParams contains all the parameters to send to the API endpoint
for the pipeline service delete pipeline version operation typically these are written to a http.Request
*/
type PipelineServiceDeletePipelineVersionParams struct {

	/*PipelineID
	  Required input. ID of the parent pipeline.

	*/
	PipelineID string
	/*PipelineVersionID
	  Required input. The ID of the pipeline version to be deleted.

	*/
	PipelineVersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the pipeline service delete pipeline version params
func (o *PipelineServiceDeletePipelineVersionParams) WithTimeout(timeout time.Duration) *PipelineServiceDeletePipelineVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pipeline service delete pipeline version params
func (o *PipelineServiceDeletePipelineVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pipeline service delete pipeline version params
func (o *PipelineServiceDeletePipelineVersionParams) WithContext(ctx context.Context) *PipelineServiceDeletePipelineVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pipeline service delete pipeline version params
func (o *PipelineServiceDeletePipelineVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pipeline service delete pipeline version params
func (o *PipelineServiceDeletePipelineVersionParams) WithHTTPClient(client *http.Client) *PipelineServiceDeletePipelineVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pipeline service delete pipeline version params
func (o *PipelineServiceDeletePipelineVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPipelineID adds the pipelineID to the pipeline service delete pipeline version params
func (o *PipelineServiceDeletePipelineVersionParams) WithPipelineID(pipelineID string) *PipelineServiceDeletePipelineVersionParams {
	o.SetPipelineID(pipelineID)
	return o
}

// SetPipelineID adds the pipelineId to the pipeline service delete pipeline version params
func (o *PipelineServiceDeletePipelineVersionParams) SetPipelineID(pipelineID string) {
	o.PipelineID = pipelineID
}

// WithPipelineVersionID adds the pipelineVersionID to the pipeline service delete pipeline version params
func (o *PipelineServiceDeletePipelineVersionParams) WithPipelineVersionID(pipelineVersionID string) *PipelineServiceDeletePipelineVersionParams {
	o.SetPipelineVersionID(pipelineVersionID)
	return o
}

// SetPipelineVersionID adds the pipelineVersionId to the pipeline service delete pipeline version params
func (o *PipelineServiceDeletePipelineVersionParams) SetPipelineVersionID(pipelineVersionID string) {
	o.PipelineVersionID = pipelineVersionID
}

// WriteToRequest writes these params to a swagger request
func (o *PipelineServiceDeletePipelineVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param pipeline_id
	if err := r.SetPathParam("pipeline_id", o.PipelineID); err != nil {
		return err
	}

	// path param pipeline_version_id
	if err := r.SetPathParam("pipeline_version_id", o.PipelineVersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
