apiVersion: v1
kind: ConfigMap
metadata:
  # NOTE: CI test reporting reads this ConfigMap name to determine whether archiveLogs is enabled.
  # If you rename it, also update:
  # backend/test/testutil/archived_workflow_logs.go
  name: workflow-controller-configmap
data:
  # References:
  # * https://github.com/argoproj/argo-workflows/blob/v3.7.3/config/config.go
  # * https://github.com/argoproj/argo-workflows/blob/v3.7.3/docs/workflow-controller-configmap.md
  # * https://github.com/argoproj/argo-workflows/blob/v3.7.3/docs/workflow-controller-configmap.yaml


  # In artifactRepository.s3.endpoint, $(kfp-namespace) is needed, because in multi-user mode, pipelines may run in other namespaces.
artifactRepository:
  archiveLogs: true
  s3:
    endpoint: seaweedfs:9000   # temp placeholder
    bucket: dummy-bucket              # temp placeholder
    keyFormat: private-artifacts/{{workflow.namespace}}/{{workflow.name}}/{{workflow.creationTimestamp.Y}}/{{workflow.creationTimestamp.m}}/{{workflow.creationTimestamp.d}}/{{pod.name}}
    insecure: true
    accessKeySecret:
      name: mlpipeline-minio-artifact
      key: accesskey
    secretKeySecret:
      name: mlpipeline-minio-artifact
      key: secretkey
  executor: |
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
