# coding: utf-8

# Copyright 2026 The Kubeflow Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
    Kubeflow Pipelines API

    Smoke tests for generated task-related client endpoints.

    Kept outside python_http_client/ because that directory is wiped and
    regenerated by build_kfp_server_api_python_package.sh.
"""

from __future__ import absolute_import

import os
import sys
import unittest

_CLIENT_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "python_http_client")
)
if _CLIENT_ROOT not in sys.path:
    sys.path.insert(0, _CLIENT_ROOT)

from kfp_server_api.api.artifact_service_api import ArtifactServiceApi
from kfp_server_api.api.run_service_api import RunServiceApi


class RecordingApiClient(object):
    """Captures generated client calls without performing HTTP."""

    def __init__(self):
        self.calls = []
        self.client_side_validation = True

    def select_header_accept(self, accepts):
        return accepts[0] if accepts else None

    def select_header_content_type(self, content_types):
        return content_types[0] if content_types else None

    def call_api(
        self,
        resource_path,
        method,
        path_params=None,
        query_params=None,
        header_params=None,
        body=None,
        post_params=None,
        files=None,
        response_type=None,
        auth_settings=None,
        async_req=None,
        _return_http_data_only=None,
        _preload_content=True,
        _request_timeout=None,
        collection_formats=None,
    ):
        del post_params, files, async_req, _return_http_data_only
        del _preload_content, _request_timeout, collection_formats

        rendered_path = resource_path
        for key, value in (path_params or {}).items():
            rendered_path = rendered_path.replace("{%s}" % key, str(value))
        self.calls.append(
            {
                "method": method,
                "path": rendered_path,
                "body": body,
                "query_params": list(query_params or []),
                "headers": dict(header_params or {}),
                "response_type": response_type,
                "auth_settings": list(auth_settings or []),
            }
        )
        return {"ok": True}


class TestGeneratedTaskEndpoints(unittest.TestCase):
    """Smoke tests for generated task-related methods."""

    def test_artifact_service_task_methods_use_expected_routes(self):
        client = RecordingApiClient()
        api = ArtifactServiceApi(api_client=client)

        create_body = {"artifact_id": "artifact-1", "task_id": "task-1"}
        api.create_artifact_task(create_body)
        api.list_artifact_tasks(task_ids=["task-1"], run_ids=["run-1"], page_size=10)

        self.assertEqual(
            [
                {
                    "method": "POST",
                    "path": "/apis/v2beta1/artifact_tasks",
                    "body": create_body,
                    "query_params": [],
                    "headers": {
                        "Accept": "application/json",
                        "Content-Type": "application/json",
                    },
                    "response_type": "V2beta1ArtifactTask",
                    "auth_settings": ["Bearer"],
                },
                {
                    "method": "GET",
                    "path": "/apis/v2beta1/artifact_tasks",
                    "body": None,
                    "query_params": [
                        ("task_ids", ["task-1"]),
                        ("run_ids", ["run-1"]),
                        ("page_size", 10),
                    ],
                    "headers": {"Accept": "application/json"},
                    "response_type": "V2beta1ListArtifactTasksResponse",
                    "auth_settings": ["Bearer"],
                },
            ],
            client.calls,
        )

    def test_run_service_task_methods_use_expected_routes(self):
        client = RecordingApiClient()
        api = RunServiceApi(api_client=client)

        create_body = {"task_id": "task-1"}
        batch_body = {"tasks": []}
        api.create_task("run-1", create_body)
        api.get_task("run-1", "task-1")
        api.list_tasks("run-1", page_size=10)
        api.batch_update_tasks("run-1", batch_body)

        self.assertEqual(
            [
                {
                    "method": "POST",
                    "path": "/apis/v2beta1/runs/run-1/tasks",
                    "body": create_body,
                    "query_params": [],
                    "headers": {
                        "Accept": "application/json",
                        "Content-Type": "application/json",
                    },
                    "response_type": "V2beta1PipelineTask",
                    "auth_settings": ["Bearer"],
                },
                {
                    "method": "GET",
                    "path": "/apis/v2beta1/runs/run-1/tasks/task-1",
                    "body": None,
                    "query_params": [],
                    "headers": {"Accept": "application/json"},
                    "response_type": "V2beta1PipelineTask",
                    "auth_settings": ["Bearer"],
                },
                {
                    "method": "GET",
                    "path": "/apis/v2beta1/runs/run-1/tasks",
                    "body": None,
                    "query_params": [("page_size", 10)],
                    "headers": {"Accept": "application/json"},
                    "response_type": "V2beta1ListTasksResponse",
                    "auth_settings": ["Bearer"],
                },
                {
                    "method": "POST",
                    "path": "/apis/v2beta1/runs/run-1/tasks:batchUpdate",
                    "body": batch_body,
                    "query_params": [],
                    "headers": {
                        "Accept": "application/json",
                        "Content-Type": "application/json",
                    },
                    "response_type": "V2beta1UpdateTasksBulkResponse",
                    "auth_settings": ["Bearer"],
                },
            ],
            client.calls,
        )


if __name__ == "__main__":
    unittest.main()
