apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pipelineversions.pipelines.kubeflow.org
  annotations:
    cert-manager.io/inject-ca-from: NAMESPACE_PLACEHOLDER/CERT_NAME_PLACEHOLDER
