// Code generated by go-swagger; DO NOT EDIT.

package artifact_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kubeflow/pipelines/backend/api/v2beta1/go_http_client/artifact_model"
)

// NewBatchCreateArtifactsParams creates a new BatchCreateArtifactsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBatchCreateArtifactsParams() *BatchCreateArtifactsParams {
	return &BatchCreateArtifactsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBatchCreateArtifactsParamsWithTimeout creates a new BatchCreateArtifactsParams object
// with the ability to set a timeout on a request.
func NewBatchCreateArtifactsParamsWithTimeout(timeout time.Duration) *BatchCreateArtifactsParams {
	return &BatchCreateArtifactsParams{
		timeout: timeout,
	}
}

// NewBatchCreateArtifactsParamsWithContext creates a new BatchCreateArtifactsParams object
// with the ability to set a context for a request.
func NewBatchCreateArtifactsParamsWithContext(ctx context.Context) *BatchCreateArtifactsParams {
	return &BatchCreateArtifactsParams{
		Context: ctx,
	}
}

// NewBatchCreateArtifactsParamsWithHTTPClient creates a new BatchCreateArtifactsParams object
// with the ability to set a custom HTTPClient for a request.
func NewBatchCreateArtifactsParamsWithHTTPClient(client *http.Client) *BatchCreateArtifactsParams {
	return &BatchCreateArtifactsParams{
		HTTPClient: client,
	}
}

/*
BatchCreateArtifactsParams contains all the parameters to send to the API endpoint

	for the batch create artifacts operation.

	Typically these are written to a http.Request.
*/
type BatchCreateArtifactsParams struct {

	// Body.
	Body *artifact_model.V2beta1CreateArtifactsBulkRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the batch create artifacts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BatchCreateArtifactsParams) WithDefaults() *BatchCreateArtifactsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the batch create artifacts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BatchCreateArtifactsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the batch create artifacts params
func (o *BatchCreateArtifactsParams) WithTimeout(timeout time.Duration) *BatchCreateArtifactsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the batch create artifacts params
func (o *BatchCreateArtifactsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the batch create artifacts params
func (o *BatchCreateArtifactsParams) WithContext(ctx context.Context) *BatchCreateArtifactsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the batch create artifacts params
func (o *BatchCreateArtifactsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the batch create artifacts params
func (o *BatchCreateArtifactsParams) WithHTTPClient(client *http.Client) *BatchCreateArtifactsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the batch create artifacts params
func (o *BatchCreateArtifactsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the batch create artifacts params
func (o *BatchCreateArtifactsParams) WithBody(body *artifact_model.V2beta1CreateArtifactsBulkRequest) *BatchCreateArtifactsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the batch create artifacts params
func (o *BatchCreateArtifactsParams) SetBody(body *artifact_model.V2beta1CreateArtifactsBulkRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *BatchCreateArtifactsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
