apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: ml-pipeline-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-pipeline-ui
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: ml-pipeline-ui
    spec:
      serviceAccountName: ml-pipeline-ui
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ml-pipeline-ui
          image: ghcr.io/kubeflow/kfp-frontend:2.16.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http

          env:
            - name: VIEWER_TENSORBOARD_POD_TEMPLATE_SPEC_PATH
              value: /etc/config/viewer-pod-template.json

            - name: MINIO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: accesskey
                  name: mlpipeline-minio-artifact

            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secretkey
                  name: mlpipeline-minio-artifact

            - name: ALLOW_CUSTOM_VISUALIZATIONS
              value: "true"

            - name: FRONTEND_SERVER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: ARGO_ARCHIVE_LOGS
              value: "true"

            - name: DISABLE_GKE_METADATA
              value: "true"

            - name: CLUSTER_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: CLUSTER_DOMAIN
                  name: pipeline-install-config
                  optional: true

            - name: ARTIFACTS_SERVICE_PROXY_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: ARTIFACTS_PROXY_ENABLED
                  name: pipeline-install-config
                  optional: true

          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true

          livenessProbe:
            httpGet:
              path: /apis/v1beta1/healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2

          readinessProbe:
            httpGet:
              path: /apis/v1beta1/healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2

          resources:
            requests:
              cpu: 10m
              memory: 70Mi

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 0
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault

      volumes:
        - name: config-volume
          configMap:
            name: ml-pipeline-ui-configmap
