apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: ml-pipeline-ui
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: ml-pipeline-ui
