apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
- ../../dev
- ../base
- namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: kfp-dev-params
  literals:
  - namespace=kubeflow

replacements:
- source:
    kind: ConfigMap
    name: kfp-dev-params
    fieldPath: data.namespace
  targets:
  - select:
      kind: Namespace
    fieldPaths:
    - metadata.name
- source:
    kind: ConfigMap
    name: pipeline-install-config
    fieldPath: metadata.namespace
  targets:
  - select:
      kind: Certificate
      name: kfp-cache-cert
    fieldPaths:
    - spec.dnsNames.1
    - spec.dnsNames.2
    options:
      delimiter: .
      index: 1
  - select:
      kind: MutatingWebhookConfiguration
      name: cache-webhook-kubeflow
    fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
      index: 0
  - select:
      kind: MutatingWebhookConfiguration
      name: cache-webhook-kubeflow
    fieldPaths:
    - webhooks.0.name
    options:
      delimiter: .
      index: 1
  - select:
      kind: MutatingWebhookConfiguration
      name: cache-webhook-kubeflow
    fieldPaths:
    - webhooks.0.clientConfig.service.namespace

# Pass proper arguments to cache-server to use cert-manager certificate
# Delete the cache deployer as we use the cert-manager instead 
patches:
- path: ./delete-cache-deployer.yaml
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--tls_cert_filename=tls.crt"
  target:
    kind: Deployment
    name: cache-server
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--tls_key_filename=tls.key"
  target:
    kind: Deployment
    name: cache-server
