apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
- ../../dev
- namespace.yaml

replacements:
- source:
    kind: ConfigMap
    name: pipeline-install-config
    fieldPath: metadata.namespace
  targets:
  - select:
      kind: Namespace
    fieldPaths:
    - metadata.name
