# proto-file: third_party/py/google_cloud_pipeline_components/templates_in_gallery/protos/gallery_metadata.proto
# proto-message: GalleryMetadata

# Forked from google3/third_party/py/google_cloud_pipeline_components/templates_in_gallery/protos/gallery_metadata_sample.textproto
upload_template_request {
  vertex_template_gallery_metadata {
    # Refer to
    # https://source.corp.google.com/piper///depot/google3/google/devtools/artifactregistry/main/kfp_artifact.proto;rcl=536882057;l=27
    # for the list of options.
    #
    # And if you would like to propose some new categorization or types, please review
    # https://docs.google.com/spreadsheets/d/16em2Dp-sHpJW61rP8SiItyty2Dor4DquDORQEIWyo-0/edit?resourcekey=0-pMwjYRX_DwHd1U0lRdEWEA#gid=0
    # and contact @desmliu
    vertex_gallery_categorization {
      type: COMPONENT
      integration: VERTEX_AI
    }
    # This field is a temporary solution. Will remove shortly after b/285601340.
    # Please add display name in the python file, example of
    # http://google3/third_party/py/google_cloud_pipeline_components/google_cloud_pipeline_components/google/template_in_gallery_test/python/component.py;rcl=529459116.
    # TODO(b/285601340) remove this field.
    display_name: "Vertex AI Custom Job Component"
  }
  # This field is a temporary solution. Will remove shortly after b/285601340.
  # Please add description in the python file, example of
  # http://google3/third_party/py/google_cloud_pipeline_components/google_cloud_pipeline_components/google/template_in_gallery_test/python/component.py;rcl=529459116.
  # TODO(b/285601340) remove this field.
  description: "Launch a Custom training job using Vertex CustomJob API."
}
pipeline_func: "google_cloud_pipeline_components.v1.custom_job.CustomTrainingJobOp"
