# proto-file: third_party/py/google_cloud_pipeline_components/templates_in_gallery/build_utils/gallery_metadata.proto
# proto-message: GalleryMetadata

upload_template_request {
  tags: "__GCPC_VERSION__"
  vertex_template_gallery_metadata {
    launch_stage: "GA"
    vertex_gallery_categorization {
      type: COMPONENT
      integration: VERTEX_AI
    }
    # Prefer to add display name in the python file, example of
    # http://google3/third_party/py/google_cloud_pipeline_components/google_cloud_pipeline_components/google/template_in_gallery_test/python/component.py;rcl=529459116.
    display_name: "Vertex AI Custom Job Component"
  }
  # Prefer to add description in the python file, example of
  # http://google3/third_party/py/google_cloud_pipeline_components/google_cloud_pipeline_components/google/template_in_gallery_test/python/component.py;rcl=529459116.
  description: "Launch a Custom training job using Vertex CustomJob API."
}
component_info {
  component_type: "gcpc-serverless-custom-job-launcher"
}
pipeline_func: "google_cloud_pipeline_components.google_cloud_pipeline_components.v1.custom_job.component.custom_training_job"
