name: KFP Backend Tests

on:
  merge_group:
    types: [checks_requested]
    branches: [release-2.18]
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'backend/**'
      - 'test/cache-deployer/**'
      - 'test/presubmit-backend-test.sh'


permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up Go
      uses: ./.github/actions/setup-go

    - name: Run Backend Tests
      env:
        GIT_BRANCH: ${{ github.event_name == 'merge_group' && github.sha || github.head_ref || github.ref_name }}
        GIT_REPO: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      run: |
        ./test/presubmit-backend-test.sh
