name: KFP SDK Upgrade Test

on:
  push:
    branches: [master]

  pull_request:
    paths:
      - 'sdk/python/**'
      - 'test/presubmit-test-sdk-upgrade.sh'
      - '.github/workflows/sdk-upgrade.yml'
      - '.github/actions/setup-python-pip-cache/**'
      - '!**/*.md'
      - '!**/OWNERS'


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-upgrade-kfp-sdk:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: ./.github/actions/setup-python-pip-cache
        with:
          python-version: 3.9
          cache-scope: sdk-upgrade
          cache-dependency-hash: ${{ hashFiles('sdk/python/requirements*.txt') }}

      - name: Install protobuf dependencies & kfp-pipeline-spec
        id: install-protobuf-deps
        uses: ./.github/actions/protobuf
        with:
          generate_golang_proto: "false"

      - name: Run SDK upgrade tests
        run: ./test/presubmit-test-sdk-upgrade.sh
