name: KFP SDK YAPF Tests

on:
  push:
    branches: [master]

  pull_request:
    paths:
      - 'api/**'
      - 'sdk/python/**'
      - 'sdk/Makefile'
      - 'test/presubmit-yapf-sdk.sh'
      - '.github/workflows/sdk-yapf.yml'
      - '!**/*.md'
      - '!**/OWNERS'


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  yapf-sdk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install YAPF SDK test dependencies
      run: make -C sdk install-test-yapf-deps

    - name: Run YAPF SDK Tests
      run: make -C sdk test-yapf
