name: KFP upgrade tests

env:
  TESTS_DIR: "./backend/test/v2/api"
  TESTS_LABEL: "ApiServerTests"
  NUMBER_OF_PARALLEL_NODES: 15
  CLUSTER_NAME: "kfp"
  NAMESPACE: "kubeflow"
  PYTHON_VERSION: "3.9"
  SKIP_OPERATOR_DEPLOYMENT: ${{ github.repository_owner != 'opendatahub-io' }}

on:
  push:
    branches:
      - master

  pull_request:
    paths:
      - '.github/workflows/upgrade-test.yml'
      - '.github/workflows/image-builds.yml'
      - '.github/actions/create-cluster/**'
      - '.github/actions/deploy/**'
      - '.github/resources/**'
      - 'backend/api/v2beta1/**'
      - 'backend/src/**'
      - 'backend/metadata_writer/**'
      - 'backend/test/v2/api/**'
      - 'manifests/kustomize/**'
      - 'test_data/sdk_compiled_pipelines/**'
      - '!**/*.md'
      - '!**/OWNERS'

jobs:
  build:
    uses: ./.github/workflows/image-builds.yml

  upgrade-test:
    if: github.repository_owner == 'opendatahub-io'
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [ "v1.34.0" ]
        tls_enabled : [ "true" ]
    name: KFP upgrade tests - K8s ${{ matrix.k8s_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.9

      - name: Create cluster
        uses: ./.github/actions/create-cluster
        id: create-cluster
        with:
          k8s_version: ${{ matrix.k8s_version }}

      - name: Deploy Last Release
        id: deploy-release
        uses: ./.github/actions/deploy
        with:
          image_path: ''
          image_path_prefix: 'opendatahub/ds-pipelines-'
          image_tag: "odh-stable"
          image_registry: "quay.io"
          pod_to_pod_tls_enabled: ${{ matrix.tls_enabled }}
          operator_image_tag: "odh-stable"
          skip_load_docker_images: 'true'
          skip_operator_deployment: ${{ env.SKIP_OPERATOR_DEPLOYMENT }}
          operator_branch: 'stable'

      - name: Configure Cluster CA e2e for TLS-Enabled Tests
        shell: bash
        run: |
          if [ "${{ env.SKIP_OPERATOR_DEPLOYMENT }}" == "false" ]; then
            kubectl get configmap openshift-service-ca.crt -n kubeflow -o jsonpath='{.data.service-ca\.crt}' > "${{ github.workspace }}/ca.crt"
          else
            kubectl get secret kfp-api-tls-cert -n kubeflow -o jsonpath='{.data.ca\.crt}' | base64 -d > "${{ github.workspace }}/ca.crt"
          fi
          echo "CA_CERT_PATH=${{ github.workspace }}/ca.crt" >> "$GITHUB_ENV"

      - name: Prepare for Upgrade
        id: prepare-upgrade
        uses: ./.github/actions/test-and-report
        if: ${{ steps.deploy-release.outcome == 'success' }}
        with:
          test_directory: ${{ env.TESTS_DIR }}
          test_label: "UpgradePreparation"
          num_parallel_nodes: ${{ env.NUMBER_OF_PARALLEL_NODES }}
          default_namespace: ${{ env.NAMESPACE }}
          python_version: ${{ env.PYTHON_VERSION }}
          report_name: "Upgrade Preparation"
          tls_enabled: ${{ matrix.tls_enabled }}
          ca_cert_path: ${{ env.CA_CERT_PATH }}
          # Deployment metadata from deploy-release action
          deployment_name: ${{ steps.deploy-release.outputs.deployment_name }}
          deployment_service_account_name: ${{ steps.deploy-release.outputs.service_account_name }}
          pipeline_runner_service_account_name: ${{ steps.deploy-release.outputs.pipeline_runner_service_account }}
          deployment_mode: ${{ steps.deploy-release.outputs.deployment_mode }}

      - name: Deploy from Branch
        uses: ./.github/actions/deploy
        if: ${{ steps.create-cluster.outcome == 'success' }}
        id: deploy
        with:
          image_path: ${{ needs.build.outputs.IMAGE_PATH }}
          image_tag: ${{ needs.build.outputs.IMAGE_TAG }}
          image_registry: ${{ needs.build.outputs.IMAGE_REGISTRY }}
          forward_port: 'false'
          skip_operator_deployment: ${{ env.SKIP_OPERATOR_DEPLOYMENT }}
          pod_to_pod_tls_enabled: ${{ matrix.tls_enabled }}

      - name: Verify Upgrade
        uses: ./.github/actions/test-and-report
        if: ${{ steps.deploy.outcome == 'success' }}
        with:
          test_directory: ${{ env.TESTS_DIR }}
          test_label: "UpgradeVerification"
          num_parallel_nodes: ${{ env.NUMBER_OF_PARALLEL_NODES }}
          default_namespace: ${{ env.NAMESPACE }}
          python_version: ${{ env.PYTHON_VERSION }}
          report_name: "Upgrade Verification"
          tls_enabled: ${{ matrix.tls_enabled }}
          ca_cert_path: ${{ env.CA_CERT_PATH }}
          # Deployment metadata from deploy action
          deployment_name: ${{ steps.deploy.outputs.deployment_name }}
          deployment_service_account_name: ${{ steps.deploy.outputs.service_account_name }}
          pipeline_runner_service_account_name: ${{ steps.deploy.outputs.pipeline_runner_service_account }}
          deployment_mode: ${{ steps.deploy.outputs.deployment_mode }}
