// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-swagger; DO NOT EDIT.

package job_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListJobsParams creates a new ListJobsParams object
// with the default values initialized.
func NewListJobsParams() *ListJobsParams {
	var (
		resourceReferenceTypeDefault = string("UNKNOWN_RESOURCE_TYPE")
	)
	return &ListJobsParams{
		ResourceReferenceType: &resourceReferenceTypeDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewListJobsParamsWithTimeout creates a new ListJobsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListJobsParamsWithTimeout(timeout time.Duration) *ListJobsParams {
	var (
		resourceReferenceTypeDefault = string("UNKNOWN_RESOURCE_TYPE")
	)
	return &ListJobsParams{
		ResourceReferenceType: &resourceReferenceTypeDefault,

		timeout: timeout,
	}
}

// NewListJobsParamsWithContext creates a new ListJobsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListJobsParamsWithContext(ctx context.Context) *ListJobsParams {
	var (
		resourceReferenceTypeDefault = string("UNKNOWN_RESOURCE_TYPE")
	)
	return &ListJobsParams{
		ResourceReferenceType: &resourceReferenceTypeDefault,

		Context: ctx,
	}
}

// NewListJobsParamsWithHTTPClient creates a new ListJobsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListJobsParamsWithHTTPClient(client *http.Client) *ListJobsParams {
	var (
		resourceReferenceTypeDefault = string("UNKNOWN_RESOURCE_TYPE")
	)
	return &ListJobsParams{
		ResourceReferenceType: &resourceReferenceTypeDefault,
		HTTPClient:            client,
	}
}

/*ListJobsParams contains all the parameters to send to the API endpoint
for the list jobs operation typically these are written to a http.Request
*/
type ListJobsParams struct {

	/*PageSize*/
	PageSize *int32
	/*PageToken*/
	PageToken *string
	/*ResourceReferenceID
	  Required field. The ID of the resource that referred to.

	*/
	ResourceReferenceID *string
	/*ResourceReferenceType
	  Required field. The type of the resource that referred to.

	*/
	ResourceReferenceType *string
	/*SortBy
	  Can be format of "field_name", "field_name asc" or "field_name des"
	Ascending by default.

	*/
	SortBy *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list jobs params
func (o *ListJobsParams) WithTimeout(timeout time.Duration) *ListJobsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list jobs params
func (o *ListJobsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list jobs params
func (o *ListJobsParams) WithContext(ctx context.Context) *ListJobsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list jobs params
func (o *ListJobsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list jobs params
func (o *ListJobsParams) WithHTTPClient(client *http.Client) *ListJobsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list jobs params
func (o *ListJobsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPageSize adds the pageSize to the list jobs params
func (o *ListJobsParams) WithPageSize(pageSize *int32) *ListJobsParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the list jobs params
func (o *ListJobsParams) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WithPageToken adds the pageToken to the list jobs params
func (o *ListJobsParams) WithPageToken(pageToken *string) *ListJobsParams {
	o.SetPageToken(pageToken)
	return o
}

// SetPageToken adds the pageToken to the list jobs params
func (o *ListJobsParams) SetPageToken(pageToken *string) {
	o.PageToken = pageToken
}

// WithResourceReferenceID adds the resourceReferenceID to the list jobs params
func (o *ListJobsParams) WithResourceReferenceID(resourceReferenceID *string) *ListJobsParams {
	o.SetResourceReferenceID(resourceReferenceID)
	return o
}

// SetResourceReferenceID adds the resourceReferenceId to the list jobs params
func (o *ListJobsParams) SetResourceReferenceID(resourceReferenceID *string) {
	o.ResourceReferenceID = resourceReferenceID
}

// WithResourceReferenceType adds the resourceReferenceType to the list jobs params
func (o *ListJobsParams) WithResourceReferenceType(resourceReferenceType *string) *ListJobsParams {
	o.SetResourceReferenceType(resourceReferenceType)
	return o
}

// SetResourceReferenceType adds the resourceReferenceType to the list jobs params
func (o *ListJobsParams) SetResourceReferenceType(resourceReferenceType *string) {
	o.ResourceReferenceType = resourceReferenceType
}

// WithSortBy adds the sortBy to the list jobs params
func (o *ListJobsParams) WithSortBy(sortBy *string) *ListJobsParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the list jobs params
func (o *ListJobsParams) SetSortBy(sortBy *string) {
	o.SortBy = sortBy
}

// WriteToRequest writes these params to a swagger request
func (o *ListJobsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int32
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {
			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}

	}

	if o.PageToken != nil {

		// query param page_token
		var qrPageToken string
		if o.PageToken != nil {
			qrPageToken = *o.PageToken
		}
		qPageToken := qrPageToken
		if qPageToken != "" {
			if err := r.SetQueryParam("page_token", qPageToken); err != nil {
				return err
			}
		}

	}

	if o.ResourceReferenceID != nil {

		// query param resource_reference.id
		var qrResourceReferenceID string
		if o.ResourceReferenceID != nil {
			qrResourceReferenceID = *o.ResourceReferenceID
		}
		qResourceReferenceID := qrResourceReferenceID
		if qResourceReferenceID != "" {
			if err := r.SetQueryParam("resource_reference.id", qResourceReferenceID); err != nil {
				return err
			}
		}

	}

	if o.ResourceReferenceType != nil {

		// query param resource_reference.type
		var qrResourceReferenceType string
		if o.ResourceReferenceType != nil {
			qrResourceReferenceType = *o.ResourceReferenceType
		}
		qResourceReferenceType := qrResourceReferenceType
		if qResourceReferenceType != "" {
			if err := r.SetQueryParam("resource_reference.type", qResourceReferenceType); err != nil {
				return err
			}
		}

	}

	if o.SortBy != nil {

		// query param sort_by
		var qrSortBy string
		if o.SortBy != nil {
			qrSortBy = *o.SortBy
		}
		qSortBy := qrSortBy
		if qSortBy != "" {
			if err := r.SetQueryParam("sort_by", qSortBy); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
